### ISSUE TITLE
How to create derived items unpacking c style structs?

### ISSUE THREAD

**Issue by LucienMorey** [OpenC3/cosmos#1001]
Hi,

Is it possible to unpack arrays of c style structs  to meaningful array items in a telemetry plugin? 

I am working with NASA's cFS platform and am using COSMOS as a mock ground station for my testing. I have a packet with all of the CCSDS header information stripped off that looks similar to this:

``` c
typedef struct
{
    int32_                      last_request_statuses[3];
    CFE_TIME_SysTime_t          time_stamps[3];
    float                       wheel_speeds_rad_s[3];
    float                       wheel_torques_Nm[3];
} ReactionWheelTlm_t;
```

Where the inherited ```CFE_TIME_SysTime_t``` is comprised of

``` c
typedef struct CFE_TIME_SysTime
{
    uint32 Seconds;    /**< \brief Number of seconds since epoch */
    uint32 Subseconds; /**< \brief Number of subseconds since epoch (LSB = 2^(-32) seconds) */
} CFE_TIME_SysTime_t;
```

I see it is possible to make derived items from other information when defining a ```tlm.txt``` file. Unfortunately,  it is unclear to me how to properly use this interface. I see that I will have to define some kind of ruby class dictating the conversion using ```GENERIC_READ_CONVERSION``` but the appropriate return time is beyond me.

**Comment by jmthomas** [comment]
We do something very similar in our demo. We have the following:
```
  APPEND_ITEM TIMESEC      32 UINT   "Seconds since epoch (January 1st, 1970, midnight)"
  APPEND_ITEM TIMEUS       32 UINT   "Microseconds of second"
```
And declare PACKET_TIME as:
```
  ITEM PACKET_TIME 0 0 DERIVED "Ruby time based on TIMESEC and TIMEUS"
    READ_CONVERSION unix_time_conversion.rb TIMESEC TIMEUS
```
Where we use our internal [unix_time_conversion.rb](https://github.com/OpenC3/cosmos/blob/main/openc3/lib/openc3/conversions/unix_time_conversion.rb) class to do the conversion.
