### ISSUE TITLE
openc3cli  PLUGIN failed to install

### ISSUE THREAD

**Issue by omermesser** [OpenC3/cosmos#1012]
Hello, may I get your assitance (The ticket was closed and im not sure you recieve the notifications)

I failed to load a PLUGIN.
I managed to install the openc3cli gem, 
I set the ENV with the correct values as shown in the above comment

But I receive an error shown in the console log:
[console.log](https://github.com/OpenC3/cosmos/files/13804890/console.log)

The error is :
"plugin_install_phase1 failed due to OpenC3AuthenticationError"

Please advise and let me know if you need any more information on my behalf.

_Originally posted by @omermesser in https://github.com/OpenC3/cosmos/issues/1003#issuecomment-1873353805_

**Comment by ryanmelt** [comment]
Please do not open new tickets for earlier discussions.   See my additional comments on #1003
