### ISSUE TITLE
How can I pull in #1017 feature into cosmos-project?

### ISSUE THREAD

**Issue by rogueWookie** [OpenC3/cosmos#1032]
Hi ~ 

I wanted to take advantage of the new command/response protocol you committed yesterday in [__this ticket__](https://github.com/OpenC3/cosmos/pull/1017/files#diff-779c40e2735637d261004fe25bcf3ef7cd618ed8df91622c8084267c8a795673). My understanding is it's not yet supported in the [__cosmos-project starting point__](https://github.com/OpenC3/cosmos-project), correct? Is this an upcoming feature we can expect soon?

**Comment by jmthomas** [comment]
You can either clone the project and build from source or wait for our next release. We release monthly so since our last release was 3 weeks ago you probably don't have to wait long. :-)
