### ISSUE TITLE
tcpip_client_interface.py does not seem to work, am I doing something incorrectly?

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/cosmos#1033]
**Describe the bug**
It looks like there is an internal issue with the interface. Regardless of interface arguments, I am not able to get a successful connection. I know that the endpoint server is accepting connections (tested using third-party application)

Here is my interface configuration:
```
INTERFACE MY_DEVICE_INT openc3/interfaces/tcpip_client_interface.py <%= my_ip %> <%= my_port %> <%= my_port %> 10 10
  MAP_TARGET MY_DEVICE
```

**To Reproduce**
Create a tcpip_client_interface.py interface in plugin.txt

**Expected behavior**
Connection successful when attempting to connect

**Screenshots**
![image](https://github.com/OpenC3/cosmos/assets/111302074/f3be5180-023a-40cc-9c46-dafe2e65cb22)

**Environment (please complete the following information):**

- OS: Linux Ubuntu 20.04 LTS
- OpenC3 COSMOS Version 5.13.0
- Browser: N/A

**Comment by GTI-Dakota** [comment]
As an added informational piece, it looks as if the connection is attempting to connect twice, resulting in OSError 106.

I receive a connection each time an attempt is made.
![image](https://github.com/OpenC3/cosmos/assets/111302074/f2bdac18-b986-479d-98d4-1ce327e26fe2)

**Comment by jmthomas** [comment]
I can reproduce ... not sure what the root issue is yet.
