### ISSUE TITLE
Unable to plot telemetry items I've specified when using your new command response protocol

### ISSUE THREAD

**Issue by rogueWookie** [OpenC3/cosmos#1040]
Hi ~ 

I have replicated your file [__cmd_response_protocol.rb__](https://github.com/OpenC3/cosmos/blob/main/openc3/lib/openc3/interfaces/protocols/cmd_response_protocol.rb) with the exception to the method called `write_packet(packet)` which I've had to define as follows. This is because i'm working w/ latest release for __cosmos-project__ starter repo but I believe this replicates the same behavior. I'm attaching my full custom protocol I based off yours below (see fpga_protocol.txt).

```ruby
def write_data(packet)
    # can't seem to utilize packet.response so this seems to work instead
    @response_packet = [packet.target_name, packet.packet_name]
    return packet
end
```
I'm attaching my full protocol file just for completeness if you want to see that. Very simply, my packet protocol I believe aligns with what the [__cmd_response_protocol.rb__](https://github.com/OpenC3/cosmos/blob/main/openc3/lib/openc3/interfaces/protocols/cmd_response_protocol.rb) offers. My setup is that I have a command, that when sent, causes the target to send back a telemetry packet of two counters. One counter (x) goes up by one and (y) goes up by two. So sending a command and receiving telemetry packet should simply show these counters going up. 

For the most part, this is the behavior I see when inspecting PacketViewer. However, I'm noticing two issues when testing my [fpga_protocol.txt](https://github.com/OpenC3/cosmos/files/13906674/fpga_protocol.txt). 
 ...

1. I can send the command "COUNTERS" and receive a telemetry response that updates the telemetry packet "COUNTERS". Packet Viewer does a great job showing that. However, it appears as purple text "sometimes". My understanding is that purple text indicates nothing new has come in and so the text will turn purple after awhile. I keep getting packets though (after sending a command) and I can see the "RECEIVED_COUNT" go up and my counters x and y go up as expected. So not sure why it stays purple. Here's two readings from sending the command "COUNTERS" two times back to back in less than 3 seconds (the second reading still stays purple as you can see).

![image](https://github.com/OpenC3/cosmos/assets/119710381/15e4b3f4-3074-48cd-8114-15e0330399ab)
![image](https://github.com/OpenC3/cosmos/assets/119710381/3dafe9e0-b788-4d14-9892-0d75d74d7672)

2. I can't seem to plot my (x) and (y) counters in Telemetry Grapher. I can select them and populate the plot but nothing is showing up in the plot when i'm getting new telemetry packets in. In other words, by sending the command "COUNTERS" a new "COUNTERS" telemetry packet does come back w/ incremented values but no plot is seen. Any idea as to what is going on? Here's two plots below each one representing the action of sending a command "COUNTERS" and receiving a telemetry packet "COUNTERS". You'll notice that the y scale of the graph changes each time I send the command "COUNTERS" and get back a new telemetry packet "COUNTERS". So it does do something, just doesn't show the line plot.

![image](https://github.com/OpenC3/cosmos/assets/119710381/596d4045-04ca-4b8c-91c2-5047e41e70ba)
![image](https://github.com/OpenC3/cosmos/assets/119710381/efb7438d-46d5-44b7-8f27-92ec79724efc)

I have the following command and telemetry configuration.

__cmd.txt__
```txt
COMMAND MYTARGET COUNTERS LITTLE_ENDIAN "counters"
    #   Keyword                                Name        BitSize    Type    Min/Max/Default     Description
        APPEND_ID_PARAMETER  CMD_ID    8             UINT    1 1 1                       "Command ID"
```
__tlm.txt__
```txt
TELEMETRY MYTARGET COUNTERS LITTLE_ENDIAN "counters"
    # Keyword             Name            BitSize Type    ID      Description
    APPEND_ITEM     counterx        8          UINT            "counterx"
    APPEND_ITEM     countery        8          UINT            "countery"
```
Perhaps I need an id here? The only problem with that is the response that the target sends doesn't contain a ID. It's just a byte stream. So I haven't been defining a APPEND_ID_PARAMETER here for my telemetry packets. From reading the code of your command and response protocol it's as if I should be naming my telemetry packet after the command packet and that's how cosmos ends up correlating a telemetry response to a telemetry packet, correct?

__plugin.txt__
```txt
VARIABLE mytarget_target_name MYTARGET
TARGET MYTARGET <%= mytarget_target_name %>
INTERFACE <%= mytarget_target_name %>_INT serial_interface.rb /dev/ttyUSB0 /dev/ttyUSB0 115200 NONE 1 10 nil
    MAP_TARGET <%= mytarget_target_name %>
    PROTOCOL READ_WRITE FpgaProtocol
```

**Comment by ryanmelt** [comment]
Hi @rogueWookie - You're way into support contract realm here.   If you are interested in purchasing a support contract please reach out to sales@openc3.com
