### ISSUE TITLE
Template protocol quirks

### ISSUE THREAD

**Issue by kearneylackas** [OpenC3/cosmos#1053]
I am using the template protocol to talk to a SCPI device (a Rigol DP811A PSU). I have a command called UPDATE_CHANNEL that is called every periodically using a microservice.

Firstly, is this the recommended way to do this?

The UPDATE_CHANNEL command is below.

`COMMAND <%= target_name %> UPDATE_CHANNEL BIG_ENDIAN "Update CHANNEL packets"
  APPEND_ID_PARAMETER  CMD_ID       8    UINT    1   1   1   "Identifier"
  APPEND_PARAMETER     CHANNEL      8     UINT    1   1   1   "Channel"
  APPEND_PARAMETER     CMD_TEMPLATE 1272  STRING  ":INST CH<CHANNEL>;:OUTP?;:OUTP:MODE?;:VOLT?;:CURR?;:MEAS:ALL?;:OUTP:OVP?;:OUTP:OVP:QUES?;:OUTP:OVP:VAL?;:OUTP:OCP?;:OUTP:OCP:QUES?;:OUTP:OCP:VAL?;:OUTP:RANGE?"
  APPEND_PARAMETER     RSP_TEMPLATE 1680  STRING  "<OUTPUT_STATE>;<OUTPUT_MODE>;<VOLTAGE_SETPOINT>;<CURRENT_SETPOINT>;<OUTPUT_VOLTAGE>,<OUTPUT_CURRENT>,<OUTPUT_POWER>;<OVP_STATE>;<OVP_FAULT>;<OVP_SETPOINT>;<OCP_STATE>;<OCP_FAULT>;<OCP_SETPOINT>;<OUTPUT_RANGE>"
  APPEND_PARAMETER     RSP_PACKET   136  STRING  "CHANNEL_<CHANNEL>"
  DISABLE_MESSAGES
  HIDDEN`

I am experiencing a weird issue where it experiences repeated timeouts upon starting. After exactly 11 5s timeouts, the timeout issue goes away. Maybe coincidence but 12 5s timeouts would be 60 seconds.

![image](https://github.com/OpenC3/cosmos/assets/7752305/21a718b2-7e49-4de2-b0b7-1106c126b964)

If I don't send commands, there are no more timeout errors. Occasionally once I start spamming commands at it, it will sometimes generate more timeouts. 

![image](https://github.com/OpenC3/cosmos/assets/7752305/a2a399bf-1678-49c1-8bc5-81a32cf35968)

To diagnose, I want to verify the exact bytes being sent to the device. However, the "View Raw" button shows me the CMD_TEMPLATE, RSP_TEMPLATE, and RES_PACKET strings before injecting the <CHANNEL> value

![image](https://github.com/OpenC3/cosmos/assets/7752305/25cb7dbc-82f1-4762-9612-61ae3852adf5)

Rather, I think it should show hex equivalent of the string actually being sent to the device. This would really help me diagnose this issue.
`:INST CH1;:OUTP?;:OUTP:MODE?;:VOLT?;:CURR?;:MEAS:ALL?;:OUTP:OVP?;:OUTP:OVP:QUES?;:OUTP:OVP:VAL?;:OUTP:OCP?;:OUTP:OCP:QUES?;:OUTP:OCP:VAL?;:OUTP:RANGE?`

And related... For those fields, the bit length is required for the template string. However, the length might be different after injecting values into the string. For example, the pre-formatted string requires 158 bytes while the actual string being sent to the device is only 150 bytes.

**Comment by jmthomas** [comment]
This is getting pretty complex and specific to your hardware. If you have a support contract you can setup a call at https://www.openc3.com/demo. 

You might check your read and write timeouts specified: https://docs.openc3.com/docs/configuration/interfaces#tcpip-client-interface. I'm guessing you're sending something you don't expect and the hardware is not responding.

I do agree we should be putting the output values in the View Raw packet. Also, we're working on a new implementation of command / response protocols that should be coming out soon.
