### ISSUE TITLE
Cosmos Demo INST2 does not ACK commands

### ISSUE THREAD

**Issue by josephmartin09** [OpenC3/cosmos#1086]
**Describe the bug**
Upon sending a command to the Python-based INST2, I receive a popup declaring that the interface did not acknowledge the command within 5 seconds. Screenshot below

**To Reproduce**
1.  Install the cosmosdemo gem
2. Navigate to Command Sender
3. Send a ASCIICMD (or any command none of them work)

**Expected behavior**
I expect to see the command show up in the "Command History" box below the command.

**Screenshots**
![image](https://github.com/OpenC3/cosmos/assets/4839930/430f5ead-4519-4582-ac12-13521c79315d)

**Environment (please complete the following information):**

- OS: Ubuntu
- OpenC3 COSMOS Version 5.13.0
- Browser: Firefox

**Comment by jmthomas** [comment]
We think this is happening specifically due to the ASCIICMD. It breaks the python microservice. Will fix in the next release.
