### ISSUE TITLE
CANVASIMAGE widget does not pull from targets_modified

### ISSUE THREAD

**Issue by timothyscherer** [OpenC3/cosmos#1095]
I am using Python to generate plots from incoming data and I would like to display them nicely on a screen. When I generate this data, I `put_target_file` in `TARGET/public/*.png`, and of course it ends up in `targets_modified`. Then I include the images in my screen like so:
```
CANVAS 592 2000
  CANVASIMAGE "*.png"  0 0
END
```

This image path only appears to reference images pre-included in the plugin when it was built. It does not include the image files from `targets_modified`.

**Comment by jmthomas** [comment]
Our [ImageLoader](https://github.com/OpenC3/cosmos/blob/4a28048a2f52ebe892c2f398966dc1a0ea3ff5b6/openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/ImageLoader.js#L4) code only appears to check targets. I think we can make this work to first check target_modified.
