### ISSUE TITLE
combo_box function does not exist on python library

### ISSUE THREAD

**Issue by MightyArty** [OpenC3/cosmos#1110]
**Problem Definition**
When using your `Script Runner`, I saw an option for a combo_box functionality which is great.
I am trying to run a Python script that would include the same structure as the Script Runner should include (Suite, Group, and function name), and I'm successfully doing it, but I have encountered an issue with the `combo_box` functionality.
I saw on your repository, that under this location: https://github.com/OpenC3/cosmos/blob/v5.14.2/openc3/lib/openc3/script/script.rb
you have the `combo_box` defined, but from the Python side, I don't find any access to this function.
Is it located somewhere else in the Python library that you provided or it's just not implemented?

**Suggested Solution**
It would be nice to have this feature in the Python library as well as in the Ruby library, so we would have access to this features like `combo_box`, `vertical_message_box`, `message_box` ... And would be able to run some script that should run from the Script Runner from a different place as well.

**Comment by jmthomas** [comment]
combo_box works from both Ruby and Python. Try it out! Most of the implementation is in the backend. You can find the python implementation here: https://github.com/OpenC3/cosmos/blob/main/openc3/python/openc3/script/__init__.py
