### ISSUE TITLE
Can't get a basic button to work in a screen

### ISSUE THREAD

**Issue by shaneyost** [OpenC3/cosmos#1115]
Hi ~ 

I'm trying to get a basic button to work to turn on my power supply. The following is my screen code. I have validated that I can send the command through command sender (that part is easy). I have saved this file in my target's `/screens` folder and the filename as all lowercase. 

```text
SCREEN AUTO AUTO 1.0
VERTICAL
  BUTTON 'off' 'api.cmd("PSU ENABLE_CH1 with STATE 'OFF'")'
  BUTTON 'on' 'api.cmd("PSU ENABLE_CH1 with STATE 'ON'")'
  LABELVALUE PSU ENABLE_CH1 VALUE
END
```

I see the screen get created fine. When I click on a button the whole screen dialog will get grayed out like it's stuck. CmdTlmServer doesn't display any error messages. The only error message is from Telemetry Viewer itself saying "At undefined: (undefined) SyntaxError: Invalid or unexpected token." It doesn't tell me where the token is or what specifically is undefined. 

I've been referencing the docs and the demo examples. I see nothing wrong with how I'm using `api.cmd` here. However, commenting out the buttons the error goes away so it's apparently related to the buttons. Running out of things to try.

**Comment by ryanmelt** [comment]
Quick fix would be to remove the quotes around the state values 'ON', 'OFF', which are optional.
```
SCREEN AUTO AUTO 1.0
VERTICAL
  BUTTON 'off' 'api.cmd("PSU ENABLE_CH1 with STATE OFF")'
  BUTTON 'on' 'api.cmd("PSU ENABLE_CH1 with STATE ON")'
  LABELVALUE PSU ENABLE_CH1 VALUE
END
```
