### ISSUE TITLE
Gem file can't be uninstalled because needed by installed plugin

### ISSUE THREAD

**Issue by mdpalme** [OpenC3/cosmos#1125]
**Describe the bug**
When creating multiple targets based on the same target folder, it is not possible to upgrade the plugin for one of the targets.

**To Reproduce**

1. From the Admin Console, click the paperclip to select plugin .gem file to be installed
2. Select plugin "openc3-cosmos-dev-0.5.30.gem"
3. Our plugin has a variable target_name. Specify the target_name variable "DEV1"
4. Wait for the plugin to install successfully
5. Repeat Steps 1-4 again but specify the target_name "DEV2"
6. Now you should have 2 targets (DEV1 and DEV2) that are based on target folder "DEV"
7. From Admin Console, click the upgrade plugin button for DEV1
8. Upgrade the plugin to "openc3-cosmos-dev-0.5.31.gem". Keep the existing target_name "DEV1" and click install.
9. See the error "Processing plugin_install: openc3-cosmos-dev-0.5.31.gem - Crashed" Above the listed targets on the Admin Console page.
10. View the crash log. Notice the errors:

- RuntimeError: Gemfile openc3-cosmos-dev-0.5.30.gem can't be uninstalled because it is needed by installed plugin
- Stderr: 
  - Error installing plugin: DEFAULT:openc3-cosmos-dev-0.5.31.gem
  - Gem file openc3-cosmos-dev-0.5.30 can't be uninstalled because needed by installed plugin

[plugin.txt](https://github.com/OpenC3/cosmos/files/14439378/plugin.txt)

**Expected behavior**
I should be able to upgrade one target's plugin even if a plugin based on the same target folder exists. This was working for me in COSMOS 5.12 with the same plugin files.

**Environment (please complete the following information):**

- OS: RHEL9.2
- OpenC3 COSMOS Version 5.14.2
- Browser: Chrome Version 122.0.6261.69 (Official Build) (64-bit)

**Comment by jmthomas** [comment]
Thank you @mdpalme for reporting this. We recently merged a PR that cleans up installations upon uninstalling a plugin. We'll get this fixed in an upcoming release.
