### ISSUE TITLE
unable to find read method in  packet.read("TELM")

### ISSUE THREAD

**Issue by Lakshmi5785-dev** [OpenC3/cosmos#1127]
I am using the below code in my OpenC3 ruby procedures

packet = get_packets(id)
value = packet.read("TELM")

I endup with error "NoMethodError : undefined method `read'"
Please help

**Comment by jmthomas** [comment]
This api changed from previous versions. It returns an array of packet hashes as described in the [docs](https://docs.openc3.com/docs/guides/scripting-api#get_packets-since-503).

```
id = subscribe_packets([['INST', 'HEALTH_STATUS'], ['INST', 'ADCS']])
wait 1
id, packets = get_packets(id)
packets.each do |packet|
  puts "#{packet['PACKET_TIMESECONDS']}: #{packet['target_name']} #{packet['packet_name']}"
end
```
