### ISSUE TITLE
[Telemetry Viewer] Limits-related widgets cause TypeErrors

### ISSUE THREAD

**Issue by jwestra-carrastro** [OpenC3/cosmos#113]
When a screen contains a LIMITSBAR, VALUELIMITSBAR, etc. widget, e.g. "VALUELIMITSBAR INST TEMPS DIODE_1_TEMP", the screen will always display the limits bar in the RED_LOW region, no matter what the telemetry value is (see below).
![image](https://user-images.githubusercontent.com/97611172/187542764-e49ced1f-a9e0-4940-a866-c148087eb090.png)

Then, when one opens the built-in screen editor and closes it, the following error occurs:
 (error) TypeError: Cannot read properties of undefined (reading '0')

This issue does not appear to occur in the demo, only in custom targets.

**Comment by jmthomas** [comment]
Have you ever received any packets for that telemetry? It could be relate to stale values.

**Comment by jwestra-carrastro** [comment]
I am receiving packets that this telemetry item is contained in. This item in particular is an unused UINT16 value that is always 0, and I have labeled it as a temperature and added limits values to for demonstration purposes.
Could the issue be that the limits bar doesn't update from a default position of :RED_LOW until the value changes?

**Comment by ryanmelt** [comment]
Limits are checked every time a packet is received.   Can you share the relevant configuration file lines for the telemetry packet?

**Comment by jwestra-carrastro** [comment]
targets/INST/cmd_tlm/tlm.txt:
TELEMETRY INST TEMPS BIG_ENDIAN "Temperature Packet"
  APPEND_ITEM    DIODE_1_TEMP 32       FLOAT     "Diode 1 Temperature"

targets/INST/screens/temp.txt:
SCREEN AUTO AUTO 0.5
VERTICAL
    VALUELIMITSBAR INST TEMPS DIODE_1_TEMP
END
