### ISSUE TITLE
Handling telemetry packet with multiple channels and multiple granules of those channels

### ISSUE THREAD

**Issue by jasonsipes** [OpenC3/cosmos#1152]
I have several ccsds telemetry packets with the basic structure of:

header
granules
checksum

Each granule could have multiple channels, for instance one packet has the following definition:

```
# TELEMETRY Target Command Endianness Description 
TELEMETRY   SWP    FPP4    BIG_ENDIAN "Four Floating Potential Probe: Observe the floating potential of the spacecraft, spacecraft charging, electric field probe."
  <%= render "_ccsds_tlm.txt", locals: {apid: 20} %> 
  
  # Keyword      Name         BitOffset BitSize Type   ID            Description
  APPEND_ITEM    CH1V1SD0001            20      UINT                 "Voltage sensor-1 to skin"
  APPEND_ITEM    CH2V2SD0001            20      UINT                 "Voltage sensor-2 to skin"
  APPEND_ITEM    CH3V3SD0001            20      UINT                 "Voltage sensor-3 to skin"
  APPEND_ITEM    CH4V4SD0001            20      UINT                 "Voltage sensor-4 to skin"
  APPEND_ITEM    CH1V1SD0002            20      UINT                 "Voltage sensor-1 to skin"
  APPEND_ITEM    CH2V2SD0002            20      UINT                 "Voltage sensor-2 to skin"
  APPEND_ITEM    CH3V3SD0002            20      UINT                 "Voltage sensor-3 to skin"
  APPEND_ITEM    CH4V4SD0002            20      UINT                 "Voltage sensor-4 to skin"
  .
  .
  .
  .
  APPEND_ITEM    CH1V1SD0100            20      UINT                 "Voltage sensor-1 to skin"
  APPEND_ITEM    CH2V2SD0100            20      UINT                 "Voltage sensor-2 to skin"
  APPEND_ITEM    CH3V3SD0100            20      UINT                 "Voltage sensor-3 to skin"
  APPEND_ITEM    CH4V4SD0100            20      UINT                 "Voltage sensor-4 to skin"
  
  APPEND_ITEM    CHKSUM                 16      UINT                 "CheckSum"
```

As you can see, there are 100 granules of 4 channels where each granule contains 1 measurement for each channel.

I'm struggling to handle this data in a meaningful way. Each item needs a unique name for the definition, and when I try to use Telemetry Grapher I can only graph one of the defined packet items, so I'm only getting 1 out of every 100 measurements.

For instance, if I'm trying to look at the "Voltage sensor-1 to skin" items, there should be 100 "Voltage sensor-1 to skin" items in each packet. I've been trying to look into derived items and arrays with no luck.

How do I structure my telemetry definition, or handle the data to have 100 granules of a singular item rather than 1 granule of 100 distinct items?

If this doesn't make any sense, please let me know.

Thank you for your help!

**Comment by jmthomas** [comment]
I think the best way forward is to create a [custom protocol](https://docs.openc3.com/docs/configuration/protocols#custom-protocols) that takes your single data packet and splits the granules into separate packets. Then COSMOS will read these all as individual data points that can be graphed as usual.

Basically you'll have to implement `read_data(data)` and instead of returning the full data, you split it into 100 chunks (80 bits based on your definition) and then return that amount of data. Your packet definition will also change to simply define just the 4 items.

If you need additional support consider purchasing a support contract or buying COSMOS Enterprise Edition.
