### ISSUE TITLE
Is there a way to map targets to an interface that was created in another gem?

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/cosmos#1154]
Hello,

I have Gem A with interface A
I have Gem B with n targets

Can I upload A, and then upload B and have the targets map to interface A when the gem is installed?

Thanks,

Dakota

**Comment by ryanmelt** [comment]
Not currently, but you can do the opposite.
Install B, and then install A and map all the targets.

Your scenario is theoretically possible, but there is currently no way to reselect on already existing interface.  Adding additional target would also require restarting the Interface microservice which would cause a short downtime.

**Comment by GTI-Dakota** [comment]
Ah, good to know. I may go with that method then. Thanks!
