### ISSUE TITLE
Docker Compose Version Tag is Obsolete

### ISSUE THREAD

**Issue by schuuust** [OpenC3/cosmos#1159]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**
Docker reports `WARN[0000] /path/to/cosmos/compose.yaml: version is obsolete` when starting, running, or stopping containers. This is specifically incurred by the `version` tag in `compose-build.yaml`, `compose-dev.yaml`, and `compose.yaml`

Full text output:

```
$ ./openc3.sh stop
WARN[0000] /path/to/cosmos/compose.yaml: `version` is obsolete 
[+] Stopping 1/1
 ✔ Container cosmos-openc3-operator-1  Stopped                                 1.6s 
WARN[0000]  /path/to/cosmos/compose.yaml: `version` is obsolete 
[+] Stopping 1/1
 ✔ Container cosmos-openc3-cosmos-script-runner-api-1  Stopped                 0.6s 
WARN[0000]  /path/to/cosmos/compose.yaml: `version` is obsolete 
[+] Stopping 1/1
 ✔ Container cosmos-openc3-cosmos-cmd-tlm-api-1  Stopped                       0.6s 
WARN[0000]  /path/to/cosmos/compose.yaml: `version` is obsolete 
[+] Running 9/9
 ✔ Container cosmos-openc3-cosmos-init-1               Removed                 0.0s 
 ✔ Container cosmos-openc3-cosmos-cmd-tlm-api-1        Removed                 0.0s 
 ✔ Container cosmos-openc3-cosmos-script-runner-api-1  Removed                 0.0s 
 ✔ Container cosmos-openc3-operator-1                  Removed                 0.0s 
 ✔ Container cosmos-openc3-traefik-1                   Removed                 0.6s 
 ✔ Container cosmos-openc3-redis-1                     Removed                 0.7s 
 ✔ Container cosmos-openc3-redis-ephemeral-1           Removed                 0.6s 
 ✔ Container cosmos-openc3-minio-1                     Removed                 0.8s 
 ✔ Network openc3-cosmos-network                       Removed                 0.4s
```

**To Reproduce**

1. Go to /path/to/cosmos/
2. Run one of the following:
    - `./openc3.sh run`
    - `./openc3.sh start`
    - `./openc3.sh stop`
    - or other similar command interacting with Docker
5. See warning

**Expected behavior**
Docker Compose files do not include obsolete tags.

Docker officially obsoleted the `version` tag: [Docker Compose Issue #11628](https://github.com/docker/compose/issues/11628)

**Environment (please complete the following information):**

Ubuntu 22.04, Docker version 26.0.0

**Comment by ryanmelt** [comment]
closed by #1160
