### ISSUE TITLE
cmd_response_protocol

### ISSUE THREAD

**Issue by jmbell1989** [OpenC3/cosmos#1162]
I'm looking to create an interface that is a command response type interface with a crc at the end of the outgoing packets. I see there is now a cmd_response_protocol but no example usage. How do you define the packet response? Also I've tried to include the CRC helper protocol with no luck. Any help is appreciated!

**Comment by jmthomas** [comment]
We also need to implement the python version of the cmd/response protocol

**Comment by jmbell1989** [comment]
@jmthomas Could you please provide and example of how the cmd would look as well as how I would include it in the plugin file?

**Comment by jmthomas** [comment]
closed by #1684 and #1733
