### ISSUE TITLE
Help with Cosmos and NOS3

### ISSUE THREAD

**Issue by Simon9050** [OpenC3/cosmos#1192]
Hi, 

first of all, thank you for your work :) 

I would like to set up NOS3(CFS) and Cosmos on different VMs with different IP but I have some issues modifying the available code.  

could you please provide some suggestions ?  Do you have some examples ? 
For example do I have to modify the udp_socket / udp_interface  ? 

Thank you for your help, 

Best Regards,

**Comment by jmthomas** [comment]
All our documentation is on our website at [docs.openc3.com/docs](https://docs.openc3.com/docs). Here's some relevent documentation about [CFS](https://docs.openc3.com/docs/guides/cfs). Unfortunately we don't have the time to provide individual support on Github. If you would like to setup a support contract please reach out at sales@openc3.com.
