### ISSUE TITLE
Query on wait_check() api.

### ISSUE THREAD

**Issue by Lakshmi5785-dev** [OpenC3/cosmos#1193]
Hi tream,
     I am trying to fetch a telemetry point value of a telemetry packet. Here I am using wait_check as below
wait_check(target, packet_name, telem_point, \"!= 0\", 5)

When I run the test for the first time this fails with value of telem point received as None.
When I just re-run the test it passes.
I increased the wait time but still it fails for the first time.This happens always.
Can you please help me to solve this.

**Comment by jmthomas** [comment]
I can't reproduce:

`wait_check('INST', 'HEALTH_STATUS', 'TEMP1', '!= 0', 5)`

Works in our demo in both Ruby and Python.

Note that we recommend the alternative syntax of:

`wait_check("INST HEALTH_STATUS TEMP1 != 0", 5)`

**Comment by ryanmelt** [comment]
Note you will receive None if that packet has never been received.

**Comment by jmthomas** [comment]
Assuming the initial check was None due to packet not received. This is the expected behavior.
