### ISSUE TITLE
target generator documentation

### ISSUE THREAD

**Issue by Lakshmi5785-dev** [OpenC3/cosmos#1194]
<img width="379" alt="image" src="https://github.com/OpenC3/cosmos/assets/54974578/efc8fd1b-9032-4057-928b-7f9928414a47">

This command it should be $..\openc3.bat cli generate target BOB right?

**Comment by jmthomas** [comment]
If you followed the [Installation Guide](https://docs.openc3.com/docs/getting-started/installation) you should already be inside a cloned [openc3-project](https://github.com/OpenC3/cosmos-project) which is in your PATH (necessary for openc3.bat / openc3.sh to be resolved). Inside this project it's recommended to edit the README.md ([Markdown](https://www.markdownguide.org/)) to describe your program / project.
