### ISSUE TITLE
How to Schedule Command Sends Without Enterprise Edition?

### ISSUE THREAD

**Issue by BrandonMitch** [OpenC3/cosmos#1200]
Our project is a completely student lead organization working on a satellite mission. We would love to have a way to send commands at scheduled times when our satellite has access to the ground satiations. Looking through the docs it looks like the only way to this is with Automatic (Enterprise) and calendar (Enterprise). For our student organization, enterprise edition is not affordable for our mission so we would need another option for automatic command sends.

 Any recommendations?

**Comment by jmthomas** [comment]
Calendar is our primary way to schedule scripts to execute at future times. It is typically used with a separately developed integration to full fledged mission planning software suite. Without purchasing Enterprise Edition, you'd have to have your operators manually run your contact scripts when you have a contact. You could also mess around with [at](https://en.wikipedia.org/wiki/At_(command)).

Enterprise Edition is licensed to your mission so if your student led satellite mission is ongoing, it might make sense to get a license for user accounts, role based access control, integration with ground networks, and obviously Calendar and Autonomic. Get in touch at sales@openc3.com.
