### ISSUE TITLE
Edge time picker doesn't show AM/PM

### ISSUE THREAD

**Issue by jmthomas** [OpenC3/cosmos#1221]
Not sure why the Edge browser is different but a user reported the time picker did not show AM/PM

**Comment by ryanmelt** [comment]
Firefox seems to behave differently too.  (No time picker option at all).

**Comment by jmthomas** [comment]
Related #1177

**Comment by jmthomas** [comment]
Works with Edge Version 124.0.2478.67 (Official build) (64-bit). Probably just need to be on a more modern version of Edge.
