### ISSUE TITLE
Generic read conversion not properly decoding 29-bit signed integer

### ISSUE THREAD

**Issue by timothyscherer** [OpenC3/cosmos#1248]
I am defining a derived item (where BYTE_ is the non-derived item referencing packet data - it is ugly and I don't like it either but it was the only way to make this work). Essentially I am taking 4 bytes and packing them together to produce a 29-bit signed integer.
![image](https://github.com/OpenC3/cosmos/assets/68401889/841cec9a-6cde-456d-af23-7cb3143fae9c)

The hex value of this field is set to 0x1ffe823a, but the telemetry reports the value as a positive, even though this should be a negative number.
![image](https://github.com/OpenC3/cosmos/assets/68401889/4ebe70b7-2bae-4465-ac46-caf593d5b3cb)

- OS: Ubuntu 22.04
- OpenC3 COSMOS Version 5.15.2
- Browser: Firefox

**Comment by ryanmelt** [comment]
This isn't a bug.   The hinting in the generic conversion (INT 29), is just for others to know what the conversion will return.   The conversion code is responsible for returning a properly formatted native (to Ruby or Python) value.
