### ISSUE TITLE
make sections of webpage collapsible

### ISSUE THREAD

**Issue by 321github123** [OpenC3/cosmos#1261]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Is your feature request related to a problem? Please describe.**

Most of the web pages that support scrolling don’t have the header section separated from the body, so when I scroll to the bottom if I want to review something at the top I have to scroll back up

**Describe the solution you'd like**

Make section of webpage collapsible

For example, in script runner, could the script section be collapsible and also the log section collapsible:

![image](https://github.com/OpenC3/cosmos/assets/94007578/c3219475-5510-4a55-87d0-4480c51498d8)

**Additional context**

**Comment by sunws4me** [comment]
in the script runner page, I think the only thing that needs to be done is anchor the bottom of script running page to the web browser and then you are good.   on the bucker explorer page the top is not static or separated from the file listing.   so if I have server hundred files and scroll to the bottom, then I can't navigate, search, select different buckets without scrolling back to the top - its just a single page.  it would be nice if the scroll logic was only tied files.  in that light, anytime you have that sort of page logic (broken into 2 parts then have the divider be a common method to allow the user to view more of whatever they want.    the one thing I like about minimizing is it gets you back to the default quicker than move a divider around.
