### ISSUE TITLE
Display mnemonic on LIMITSBAR hover

### ISSUE THREAD

**Issue by sunws4me** [OpenC3/cosmos#1288]
mnemonic is available when hovering over the current tlm value, would be nice if the expression did the same when over the color bar.

**Comment by jmthomas** [comment]
Or we could alternatively show the range of the color bar: red low, yellow low, yellow high, red high

**Comment by sunws4me** [comment]
just need some way to see the actual limits, the color bar is not intuitive to tell how close to the boundary you might be.
