### ISSUE TITLE
Cosmos crushes after the modification of SAMPLE_TLM.txt file

### ISSUE THREAD

**Issue by lucapizzuto99** [OpenC3/cosmos#1297]
Hi everyone,

I wanted to modify the telemetry file of the sample subsystem, in order to add new parameters.
At first, this seemed to work, since I was able to see the new parameter with its values in the packet viewer.
However, when I tried to modify the file to add other parameters, COsmos crushed and I was not able to display the interfaces. 

I then decided to report the file to its original state, without any modification, but that didn't work.

![Screenshot from 2024-05-23 13-12-49](https://github.com/OpenC3/cosmos/assets/158168681/02e6a09d-d620-4a9d-8a61-8c23515cd0f7)

The error I get is:

`openc3cli validate openc3-cosmos-nos3-1.0.202405231232.gem
  Successfully built RubyGem
  Name: openc3-cosmos-nos3
  Version: 1.0.202405231232
  File: openc3-cosmos-nos3-1.0.202405231232.gem
Installing openc3-cosmos-nos3-1.0.202405231232.gem
Successfully validated openc3-cosmos-nos3-1.0.202405231232.gem

Load plugin...
Loading new plugin: openc3-cosmos-nos3-1.0.202405231232.gem
{"name"=>"openc3-cosmos-nos3-1.0.202405231232.gem", "variables"=>{}, "plugin_txt_lines"=>#<Array:1040>, "needs_dependencies"=>false, "updated_at"=>nil}
Error installing plugin: DEFAULT: openc3-cosmos-nos3-1.0.202405231232.gem

RuntimeError : DEFAULT__openc3_targets:GENERIC_MAG_DEBUG already exists at create
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.12.0/lib/openc3/models/model.rb:141:in `create'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.12.0/lib/openc3/models/plugin_model.rb:232:in `block in install_phase2'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.12.0/lib/openc3/config/config_parser.rb:217:in `parse_loop'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.12.0/lib/openc3/config/config_parser.rb:217:in `parse_file'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.12.0/lib/openc3/models/plugin_model.rb:226:in `install_phase2'
/openc3/bin/openc3cli:467:in `load_plugin'
/openc3/bin/openc3cli:649:in `<main>'
`

- OS: Ubuntu 22.04.3
- OpenC3 COSMOS Version 5.12.0
- Browser: Firefox

**Comment by jmthomas** [comment]
Try to load again. Sometimes you get an "already exists at create" message per #1271

**Comment by lucapizzuto99** [comment]
Hi Thomas, thanks for the quick reply.
What I did multiple times is to reverse the changes done and go back to the functioning version of the repo of one week ago, then stop cosmos (and the entire NOS3) and then re-make.
However, the issue persists.
Is this what you meant by loading again?

**Comment by jmthomas** [comment]
You might be using the old version of the Demo plugin if you edited it directly. You shouldn't be rebuilding the entire repo. Just rebuild the plugin `openc3.sh cli rake build VERSION=1.0.0` and then upload it (or update it) on the Admin screen.

**Comment by lucapizzuto99** [comment]
Hi Thomas.
I actually have installed cosmos as part of the entire NOS3 simulator, so I am not sure if this applies to my situation, like I do not have the openc3.sh file in my project.
Also, the error message is this one:

`plugin.txt20240524-7-svw1xb:92: MAP_TARGET CFDP_TEST_RADIO
Error: Unknown keyword and parameters for Target: MAP_TARGET CFDP_TEST_RADIO
Backtrace:
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.12.0/lib/openc3/models/target_model.rb:558:in `handle_config'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.12.0/lib/openc3/models/plugin_model.rb:240:in `block in install_phase2'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.12.0/lib/openc3/config/config_parser.rb:217:in `parse_loop'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.12.0/lib/openc3/config/config_parser.rb:217:in `parse_file'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.12.0/lib/openc3/models/plugin_model.rb:226:in `install_phase2'
/openc3/bin/openc3cli:467:in `load_plugin'
/openc3/bin/openc3cli:649:in `<main>'
`
The runtime error of before is not the reason why cosmos crushes, I think it has to do with this error. 

My NOS3/gsw/cosmos folder is structured in this way:
![image](https://github.com/OpenC3/cosmos/assets/158168681/9f74dae8-bae5-49f3-9443-1d33e649020e)

I am sorry but I am still new to NOS3 and Openc3.
