### ISSUE TITLE
Add ability to search by item name only

### ISSUE THREAD

**Issue by 321github123** [OpenC3/cosmos#1302]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Is your feature request related to a problem? Please describe.**
Our uses are typically more familiar with telemetry items rather than the packet the item is in.

**Describe the solution you'd like**
Add ability to search by item only e.g. when using Data Viewer.

**Additional context**

**Comment by jmthomas** [comment]
duplicate of #964
