### ISSUE TITLE
Make build_cmd timeout a variable that can be passed into call

### ISSUE THREAD

**Issue by 321github123** [OpenC3/cosmos#1316]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Is your feature request related to a problem? Please describe.**
The build_cmd call occasionally times out. When we rerun once or twice, then it succeeds.

**Describe the solution you'd like**
In python/ruby build_cmd api call "openc3.script.build_cmd", expose a time out parameter with a default value.

**Additional context**
![image](https://github.com/OpenC3/cosmos/assets/94007578/b5e0040e-8362-40ef-b1c1-8e8d1024d516)

**Comment by JoshuaNeely** [comment]
We manually increased timeout to 60s (building src code) and see the same intermittent error that made us think it was a timeout thing.

We might instead need to troubleshoot our redis connection... retry logic, etc. There's something else afoot

**Comment by ryanmelt** [comment]
Check the docker logs on the operator to see if there are any errors there.

**Comment by JoshuaNeely** [comment]
Nothing jumped out at me in the logs.

Current theory is our redis pod is maxing out it's memory allocation

**Comment by jmthomas** [comment]
closed by #1381
