### ISSUE TITLE
Microservice UDP

### ISSUE THREAD

**Issue by Ray-13** [OpenC3/cosmos#1318]
**Is your feature request related to a problem? Please describe.**

I can't find how to receive a send command from the UDP interface and target using a microservice.
Without the microservice, I manage to retrieve the order, but with it, I cannot find the solution. Do you have any suggestions or solutions?

**Describe the solution you'd like**

Example code for implementing this communication in a Python microservice for UDP.

**Additional context**

Currently, my Python microservice is configured to listen on a specific port, but it doesn't seem to receive the data sent by Cosmos OpenC3. Improved documentation and practical examples would greatly facilitate integration and debugging of this functionality.

**Comment by jmthomas** [comment]
It looks like you're trying to setup a microservice to listen on a UDP port that you want COSMOS to send to. The IP `host.docker.internal` is effectively the host machine ... not the docker container where the microservice lives. Have you tried `127.0.01` or `localhost`?

**Comment by Ray-13** [comment]
Yes, I tried but it's the same

**Comment by Ray-13** [comment]
but when I reverse the port like this: 
`  INTERFACE <%= sensehat_target_name %>_INT udp_interface.rb localhost 8081 8080 8080 none none 128 none none
`
and I send a command, the interface reacts and crashes and returns: 
` Connection refused - recvfrom(2)`

**Comment by Ray-13** [comment]
It works with localhost I forgot to change it in my microservice, thank for your help
