### ISSUE TITLE
cosmos python module finder (MyFinder) fails to handle `__init__.py` case resulting in recursion failure while importing sub-modules

### ISSUE THREAD

**Issue by ikarlinsey** [OpenC3/cosmos#1320]
***Description***
`MyFinder` is a custom module loader used by COSMOS to dynamically load Python modules from specified directories. It currently fails to handle cases where a directory with an `__init__.py` should be treated as a module, leading to a recursion failure during sub-module import.

***To Reproduce***

1. Create a submodule under a COSMOS target/lib folder and try to import it.
2. Example directory structure:
```
INST/lib/sprint/sample_print.py
INST/lib/sprint/__init__.py
INST/lib/__init__.py
INST/procedures/test_sample.py
```
3. `INST/lib/sprint/sample_print.py`:
```python
class SamplePrint():
  def __init__(self):
    pass

  def printSample(self, message):
    print(message)
``` 
4. `INST/procedures/test_sample.py`:
```
from INST.lib.sprint.sample_print import SamplePrint

sample = SamplePrint()
sample.printSample("Hello World")
``` 
5. Load `test_sample.py` in script runner and click go.
Observe the script fails on the from `INST.lib.sprint.sample_print import SamplePrint` line with the following error:
```
2024-06-05T20:42:54.240565Z (test_sample.py:3): {"time": 1717620174240564992, "@timestamp": "2024-06-05T20:42:54.240565Z", "level": "ERROR", "microservice_name": "Script Runner", "detail": "test_sample.py:3", "container_name": "1dc60fba6521", "message": "Traceback (most recent call last):\n File \"INST/procedures/test_sample.py\", line 3, in <module>\n from INST.lib.sprint.sample_print import SamplePrint\nModuleNotFoundError: No module named 'INST.lib.sprint'\n", "type": "log"}
```
***Expected behavior***
The import statement should find the submodule and load it.

***Potential Fix:***
The issue seems to arise because `MyFinder` does not account for directories with `__init__.py` files, treating them as modules. The following changes in `target_file_importer.py` address this:

Add `import os` to the top of the file.

Change starting at line 98 from:
```python
body = TargetFile.body(OPENC3_SCOPE, f"{path_name}.py")
if body is not None:
    # If a file was actually there we assign it to loader_state
    # so the loader can parse it into a real module
    spec.loader_state = body.decode()
    return spec

```
to
```python
body = TargetFile.body(OPENC3_SCOPE, f"{path_name}.py")
if body is None:
     body = TargetFile.body(OPENC3_SCOPE, os.path.join(path_name, "__init__.py"))
if body is not None:
    # If a file was actually there we assign it to loader_state
    # so the loader can parse it into a real module
    spec.loader_state = body.decode()
    return spec
```

After applying the proposed fix, the script runs successfully, and the module imports without errors.

***Environment:***
OS: Windows 11 Enterprise
OpenC3 COSMOS Version 5.16.3-beta0 & OpenC3 COSMOS Version 5.14.2
Browser: Chrome 125.0.6422.113

**Comment by jmthomas** [comment]
@ikarlinsey thanks for this detailed write up. I'll try it out!
