### ISSUE TITLE
Any alternative for cmd_tlm_clear_counters ??

### ISSUE THREAD

**Issue by Lakshmi5785-dev** [OpenC3/cosmos#1324]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

Next search the issues here on Github. If you come up empty please submit an issue.

**Comment by jmthomas** [comment]
We have the ability to clear the counters on an individual interface by doing `interface_cmd(INST_INT, "clear_counters")`, where INST_INT is the actual name of the interface you want to clear. If you want to clear all interfaces do this following:

```
target_ints = get_target_interfaces()
target_ints.each do |target_name, interfaces|
  # interfaces is a comma delimited string with all the interface names
  interfaces.split(',').each do |interface|
    interface_cmd(interface, "clear_counters")
  end
end
```
