### ISSUE TITLE
Multiline not workingi n combo_box api

### ISSUE THREAD

**Issue by Lakshmi5785-dev** [OpenC3/cosmos#1334]
combo_box("Confirm if the antenna canister has deployed and the antenna has risen from the cavity. If the canister is still stowed, escape or retry.                            \n\na> ENTER to proceed to heat filars \nb> ESCAPE to abort prior to filar heating and exit the script. \nc> RETRY to wait 10 minutes and deploy again.",                            'ENTER','ESCAPE','RETRY')

When I use the above method I got the below error.

<img width="353" alt="image" src="https://github.com/OpenC3/cosmos/assets/54974578/e58b33e9-7abc-4c5e-833d-2711ead5ff3e">

**Comment by jmthomas** [comment]
Works for me:
<img width="1193" alt="Screenshot 2024-06-14 at 9 32 44 PM" src="https://github.com/OpenC3/cosmos/assets/176403/b858b7c7-f0e4-4800-8c3f-6fabb7ffd567">

**Comment by Lakshmi5785-dev** [comment]
Ohh Yeah, when I openend new file and pasted above lines yes it worked.
When I used in my script it fail. will debug from my script perspective. Thank you for the reply.

**Comment by jmthomas** [comment]
Ok I'll close but post any additional info as you find out.
