### ISSUE TITLE
Issue with gem file

### ISSUE THREAD

**Issue by Lakshmi5785-dev** [OpenC3/cosmos#1336]
1. I have cmd,tlm files 
2. I build the Openc3 and running
3. I changed cmd,tlm files
4. I cleaned up the images and volumes from the docker desktop(I tried .\openc3 cleanup as well)
5. And hit .\openc3 start.
6. I could see it is fetching the images from CACHE and my latest cmd,tlm files are not updated

We can do it by building and loading gem file from the admin console. But I face difficulty in automating like clicking on the admin console button, the clock button etc.

so is there anyway the taget based old gem file is compleately removed and should build new gem and load it.

**Comment by jmthomas** [comment]
If you have `OPENC3_LOCAL_MODE` enabled (which it is by default) you will be creating a local `plugins` directory. This directory stores the local copies of your plugins as installed and is used when you start or run COSMOS. If you want to blow away _everything_ you can use the new `openc3.sh cleanup local` and it will also cleanup your local plugin files. If you don't want to be prompted you can add force like `openc3.sh cleanup local force`. NOTE THIS WILL DELETE ALL YOUR DATA!
