### ISSUE TITLE
Test suite and Test groups

### ISSUE THREAD

**Issue by Lakshmi5785-dev** [OpenC3/cosmos#1352]
we have several folders (ABC, XYZ, UTG, HGF), and each folder contains 10 Python files (test_one.py, test_two.py, ..., test_ten.py). Each of these folders represents a suite of test cases.

Goal:
For each suite (folder), you want to:

Traverse into the folder.
Identify all Python files that start with test_.
Read the class names defined in each of these files.
Add these class names to a set or list called add_group.

"I used the ast Python module to retrieve class names from files, which were successfully collected as strings in a list. However, add_group requires elements of type class as arguments. Do you have any suggestions on how to proceed?"

**Comment by ryanmelt** [comment]
You'll need to import each of the files and pull in the classes
