### ISSUE TITLE
Sometimes build is stuck at alpine 3.18.5

### ISSUE THREAD

**Issue by Lakshmi5785-dev** [OpenC3/cosmos#1359]
![image](https://github.com/OpenC3/cosmos/assets/54974578/a23d09e7-91d7-437b-8514-f2adc6491e0e)

Sometimes when I try to build the OpenC3 it gets stuck here.
The only solution is I need to restart my machine.
any solution for this?

**Comment by ryanmelt** [comment]
We've seen docker get stuck during builds sometimes.  Restarting docker will generally correct it.
