### ISSUE TITLE
Custom Python interfaces seem to have connect() method called twice

### ISSUE THREAD

**Issue by heyschultzy** [OpenC3/cosmos#1362]
I'm developing my own custom Python ActiveMQ interface based off of Interface class (doesn't seem to be one in your examples, other than using the MQTT interface to AMQ), but I noticed it appears to be calling my connect() method twice within about 3ms. That was with version 5.15.2, so I downloaded the latest 5.16.2 and created a *highly* useful interface called nada_interface.py that just has some stubbed-out methods for connecting, reading, etc. I noticed it seems to do the same thing:

![image](https://github.com/OpenC3/cosmos/assets/54586033/7ce5a153-9fe3-4ad5-b7a9-3d02ebe12317)

My plugin.txt looks like this for my target:

```
VARIABLE mytarget_target_name MYTARGET

TARGET MYTARGET <%= mytarget_target_name %>
INTERFACE <%= mytarget_target_name %>_INT nada_interface.py host.docker.internal 61613 61613 10.0 None
  MAP_TARGET <%= mytarget_target_name %>
```

You should be able to reproduce by stubbing out your own version of a Python interface class, or I can upload mine if you need it.

This seems to be related to this issue, but doesn't appear to be fixed for my use case:

Fix python tpcip client connection,  #1034

I'm running this on Ubuntu 22.04 in Chrome.

Thanks! ~Jeff

**Comment by heyschultzy** [comment]
Also, don't know if this is related or not, but when I click the Interface Disconnect button in the GUI, I see it log that the disconnect is requested, but when I then click the Connect button, I see that it logs a "Connect requested" but my connect() method is never called in the interface (since I'm logging that inside my interface), and it just hangs there in "Attempting" status.

**Comment by ryanmelt** [comment]
Can you post the entire nada_interface.py?

**Comment by heyschultzy** [comment]
Sure! Here it is in all its glory...
[Uploading nada_interface.py.txt…]()

**Comment by heyschultzy** [comment]
Sure! Here it is in all its glory...

[nada_interface.zip](https://github.com/user-attachments/files/15989620/nada_interface.zip)

**Comment by ryanmelt** [comment]
I think your issue is read_interface should never return empty data ''b.  That indicates a broken interface

**Comment by ryanmelt** [comment]
Also it needs to block, or you will max out the cpu with constant data

**Comment by heyschultzy** [comment]
Ok, yeah I put a sleep in there so it won't hammer the cpu, but I could make it just wait forever.

The connect() is being called twice in quick succession *before* any call to read_interface(), so I think there is still an underlying issue, no?

**Comment by ryanmelt** [comment]
I still need to look into the connect twice thing.  For now I would recommend writing your code to handle that, and just do nothing on the second connect call.

**Comment by heyschultzy** [comment]
Yup! That's what I did...
