### ISSUE TITLE
Custom tool and Custom Widget

### ISSUE THREAD

**Issue by albertkojo** [OpenC3/cosmos#1371]
So I generated a custom tool and a custom widget but for some reason I can't get them all to work together. any tips on how to fix this.

**Comment by jmthomas** [comment]
Custom widgets and custom tools should be generated in separate plugins. It's much more complex building them side by side.

**Comment by ryanmelt** [comment]
Agreed with Jason.  This falls into the "dont do that" category.  Just make two separate plugins.
