### ISSUE TITLE
Query regarding script runner log.

### ISSUE THREAD

**Issue by Lakshmi5785-dev** [OpenC3/cosmos#1372]
My script runs for 40 minutes, but the script runner log which is generated is storing the log messages for last 10minutes only. Is there a way I can save my compleate logs?

**Comment by jmthomas** [comment]
I'm not sure what you mean. The Script Runner log contains the messages from the complete script run. You can access it by selecting Script -> Execution Status and download the log. You can also access it from Bucket Explorer by navigating to `/DEFAULT/tool_logs/sr/<YYYYMMDD>`

**Comment by ryanmelt** [comment]
@jmthomas Did you verify that the scriptrunner log writer isn't creating a new file every 10 minutes?

**Comment by jmthomas** [comment]
Yes I let it run for 30min and only got a single log file.

**Comment by ryanmelt** [comment]
@Lakshmi5785-dev Please provide an example test script that we can use to recreate.

**Comment by jmthomas** [comment]
Closing due to lack of information
