### ISSUE TITLE
JSON ACCESSOR 5.17.1 Python

### ISSUE THREAD

**Issue by bradenvirdellgenevatech** [OpenC3/cosmos#1376]
Hello,

I have been trying to get the JSON accessor working within a Python Target. 

My current setup includes the following.
A Custom interface currently it just attempts to Log the cmd that was sent and then pass it off to the end point.
I Have a single command with a single parameter as shown below:
![image](https://github.com/OpenC3/cosmos/assets/111302076/d43c7db2-a9bb-4a0e-8f85-c1ab6a4a413d)
When I don't have the Accessor added I can print out the bytearray without problem, once I add the accessor I can no longer print out the expected JSON string in the custom interface and instead I get the standard command log in the CmdTlmServer and a timeout error in the command sender.

Currently I don't think I have done anything different than what I have done before in ruby based targets. Is there another thing I need to add or consider?

**Comment by jmthomas** [comment]
I can confirm that this isn't working and I get a stack trace due to assigning the template as a string and not bytes. There's also another issue in that we don't currently support `TEMPLATE_FILE` in a Python target. I'll address both in a future PR.
