### ISSUE TITLE
Add fixed whitespace to bottom of Navbar

### ISSUE THREAD

**Issue by ryanmelt** [OpenC3/cosmos#1392]
This will always allow you to scroll down to the last tool in the Navbar, and have it not be obscured by the footer.

**Comment by ryan-pratt** [comment]
This will actually be resolved by the Vuetify 3 migration. Their styling/behavior changes to v-navigation-drawer and v-app-footer result in the footer not overlapping the nav bar:
![image](https://github.com/user-attachments/assets/126eb35a-9e11-49db-a3e7-f8c00679ddc0)

**Comment by ryan-pratt** [comment]
Closing as OBE
