### ISSUE TITLE
Script fails with error 

### ISSUE THREAD

**Issue by Lakshmi5785-dev** [OpenC3/cosmos#1397]
While running my procedures all of sudden I am receiving the below error.
any clue on this?

![image](https://github.com/OpenC3/cosmos/assets/54974578/4fff76d5-0c02-4bb0-a710-7d932da90ab2)

**Comment by jmthomas** [comment]
Do a `docker ps` and then check the logs from the cmd-tlm-api container: `docker logs cosmos-openc3-cosmos-cmd-tlm-api-1`. You can also check the operator container: `docker logs cosmos-openc3-operator-1`. Post if you see any stack traces.

**Comment by Lakshmi5785-dev** [comment]
<img width="859" alt="image" src="https://github.com/user-attachments/assets/77467235-ca5b-4777-a231-f916ec344927">
[cmd_tlm_api_logs.txt](https://github.com/user-attachments/files/16195630/cmd_tlm_api_logs.txt)
[Uploading operator_logs.txt…]()

**Comment by jmthomas** [comment]
I need the logs output, not the ps output

**Comment by Lakshmi5785-dev** [comment]
Attached the test files 
[cmd_tlm_api_logs.txt](https://github.com/user-attachments/files/16195911/cmd_tlm_api_logs.txt)
[operator_logs.txt](https://github.com/user-attachments/files/16195913/operator_logs.txt)

**Comment by jmthomas** [comment]
I don't see anything that would indicate a failure in the cmd-tlm-api container or operator container.

**Comment by jmthomas** [comment]
I see you're using Python but I can not reproduce in the DEMO with a simple test: `cmd_no_hazardous_check(f"INST CLEAR")`

**Comment by Lakshmi5785-dev** [comment]
Well this error occurs when we provide wrong command parameters. Figured out the issues. Closing the ticket.

**Comment by jmthomas** [comment]
@Lakshmi5785-dev that was a really weird error message. Was there something specific about the command parameters that could reproduce it? I'd like to at least provide a better error message.

**Comment by Lakshmi5785-dev** [comment]
Let me try on INST demo target, but I am sure its because of incorrect command parameters. It happend for me couple of times. Let me reproduce and share the details here.
