### ISSUE TITLE
Data Extractor file name times not picking up current time

### ISSUE THREAD

**Issue by sunws4me** [OpenC3/cosmos#1409]
time does not change on multiple runs of data extractor over different system clock times.

setup a data extraction and repeated running over multiple seconds, however, the filename on each output was the same - the seconds field did not increment to match the actual run time

clicking into packet viewer and back to data extractor and rerunning does get a new timestamp as part of the new file name.
![image](https://github.com/user-attachments/assets/38fadd3a-d4a6-47c2-b834-2a1186a73dad)

**Comment by ryanmelt** [comment]
I think this is as expected.  The filename is based on the data extraction start time field.   (Not current system clock time)

**Comment by sunws4me** [comment]
Hello,
Just thought it was odd to have a static file name on the output, current system time is a nice incrementing value and then the user gets an easy history without doing any work to sort it out and rename files.

**Comment by ryanmelt** [comment]
We could potentially have different file naming modes, but I like how it currently works.   It relates to what you are extracting, rather than whatever time it happens to be right now.

**Comment by sunws4me** [comment]
A little confused by that,  ‘relates to what you are extracting’.  The file name stays static from when you went to the page and doesn’t change, that’s not going to relate to anything the user is doing its just a random point in time, not where they were on 9/11…..  system time as part of the output name wouldn’t relate either, just a name that would be changing over time and not include the dup markings (1), (2), …

I haven’t done the save/load, if I load a saved config, will the name of the config be part of the output name?  that would be a piece of meaningful data if its part of the filename (mine would be bob so maybe not for me!)

Since its saving to a file its really not a big deal, everything I’ve done in my history has always included system time at least so I thought it was a bug.

**Comment by ryanmelt** [comment]
Its not a random point in time.  Its the time in the start field.

**Comment by ryanmelt** [comment]
![Screenshot 2024-07-16 at 4 54 25 PM](https://github.com/user-attachments/assets/a9c6322f-5c9b-45f4-a82c-1aa57486fbe0)

**Comment by sunws4me** [comment]
Thanks I was missing that piece.
