### ISSUE TITLE
support for hexadecimal input to VARIABLE of plugin.txt

### ISSUE THREAD

**Issue by 321github123** [OpenC3/cosmos#1411]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Is your feature request related to a problem? Please describe.**
User cannot input hexadecimal in VARIABLE fields of plugin.txt

**Describe the solution you'd like**
User has ability to input hex values  in VARIABLE fields. For example, user can input  "0xDEADBEEF"  instead of "3735928559" 

**Additional context**

**Comment by ryanmelt** [comment]
VARIABLEs are just strings, so you can enter whatever you want.  
At the point of variable use with ERB, you need to handle the string correctly.
