### ISSUE TITLE
print statements in imported functions are delayed being sent to console of Script Runner

### ISSUE THREAD

**Issue by 321github123** [OpenC3/cosmos#1420]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**
If an imported function has print statements within it and the function is called, the print statements are delayed being sent to the console log in script runner

**To Reproduce**
Create helper file "INST/helper.py"

```
import time

def sleepy_function(seconds: float = 10):
  print(f"starting to sleep {seconds}")
  time.sleep(seconds)
  print("Done!")
```

In new file, execute the following code

```
from INST.helper import sleepy_function

print('hello')
sleepy_function(10)
print('bye')
```

Observe that the print statement is only outputted after the helper function has completed.

![image](https://github.com/user-attachments/assets/9d250aee-49b8-4c82-94a2-9b03195f59bd)

**Expected behavior**
Print statements of imported function are logged promptly

**Screenshots**

**Environment (please complete the following information):**

- OS: WSL Ubuntu 20.04
- OpenC3 COSMOS Version Enterprise 5.15.2
- Browser: Chrome

**Comment by ryanmelt** [comment]
This is as expected.  STDOUT is output after an instrumented line completes.   Your regular import function is not instrumented so no output until it completes.

Use load_utility if you need the output sooner:
load_utility("INST/helper")
