### ISSUE TITLE
Multiple Custom Tools

### ISSUE THREAD

**Issue by albertkojo** [OpenC3/cosmos#1428]
I want to ask if it possible to integrate two custom tools so that when I run the .gem file it builds both custom tools and how do i go about accomplishing that.

**Comment by jmthomas** [comment]
Tools are meant to be 1 per plugin which is how all the COSMOS tools are packaged. Keeping them separate also allows you to apply fixes and updates to each tool individually. Start with our [tool code generator](https://docs.openc3.com/docs/getting-started/generators#tool-generator) and build from there. Also read our [Developing](https://docs.openc3.com/docs/development/developing) guide.

**Comment by albertkojo** [comment]
I want to create two different custom tool connected to the same plugin. what recommendation do you have to go about this? Would you recommend having 2 plugins under the same target dir

**Comment by ryanmelt** [comment]
You should have two separate plugin directories, and build each one separately.

(Theoretically you can put two "built" tools into the same plugin.  But the build framework (package.json) only handles building one tool within a plugin folder structure.)

**Comment by heyschultzy** [comment]
@jmthomas Oops, I might have misled Albert there asking that question. Looks like the plugin dir is the top-level dir and the target goes underneath that. In [Getting Started](https://docs.openc3.com/docs/getting-started/gettingstarted) it says:

> The target generator creates a single target named BOB. Best practice is to create a single target per plugin to make it easier to share targets and upgrade them individually.

There doesn't appear to be much documentation, so please forward us to that if we're just missing it, but what it looks like we want to do is:

1. Create a plugin+target (e.g. BILLYBOB) for our external target. For this plugin we have a target that we have written our own ActiveMQ interface code for and defined CMD/TLM for.
2. Define a plugin+target for each custom "tab/screen/window" on the left sidebar that we want. Each of these .vue files would then be able to make js calls like this to read from BILLYBOB?
      this.api.get_tlm_packet('BILLYBOB', 'HEALTH').then((data) => {...}

Does this sound right?

**Comment by jmthomas** [comment]
You can combine a target in the same plugin as a tool but you just can't have multiple tools in one plugin. If you start with the code generators you'll see the first step is to create the plugin framework. Then you can create a target within that plugin, then create a tool within that plugin. It should all build and deploy together.

**Comment by heyschultzy** [comment]
Thanks for the reply, @jmthomas. In my example above I want to have multiple tools (step 2. multiple times). I want to have MyCoolTool1, MyCoolTool2, MyCoolTool3 in the left sidebar. Each one is interacting with the same target BILLYBOB in the BILLYBOB plugin. Does this break the OpenC3 tool paradigm?

E.g. this would be similar to the way the other built-in tools work: the "Telemetry Viewer" and "Packet Viewer" tools can access any of the targets/commands/telemetry items.

**Comment by jmthomas** [comment]
All the tools can access all the target telemetry. It is a many to many relationship. They do not have to be bundled together. In fact like we said, you need one tool per plugin. I would probably suggest getting the target info in a separate plugin as well. So for tools MyCoolTool1, MyCoolTool2, MyCoolTool3 and target BILLYBOB you'd have 4 plugins. Simply install them all separately and they all get to play together.

**Comment by heyschultzy** [comment]
Sounds good--we'll give it a whirl!
