### ISSUE TITLE
Clear Telemetry Grapher graph data

### ISSUE THREAD

**Issue by 321github123** [OpenC3/cosmos#1429]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Is your feature request related to a problem? Please describe.**
User would like to clear our all currently plotted telemetry items within a Telemetry Grapher graph

**Describe the solution you'd like**
Add "reset" button that clears out all previously plotted telemetry items to a Telemetry Grapher graph

**Additional context**

**Comment by jmthomas** [comment]
We have a File menu option to reset Telemetry Grapher that clears everything and closes the graph.

**Comment by 321github123** [comment]
Would it be possible to add a reset button that clears the graph but doesn't close it?

**Comment by jmthomas** [comment]
Keep all the graph items but just clear the graph?

**Comment by 321github123** [comment]
Yes -- maybe the button should be called "clear"

**Comment by ryanmelt** [comment]
I think there are two different capabilities mentioned here:
1. Clear all the data from a graph
2. Remove all the items from a graph?

**Comment by jmthomas** [comment]
We already have the capability to clear the graph completely (remove all the items and data) via the File->Reset Configuration. I think the ability to clear all the data but keep the items is a nice feature. Not sure exactly where the right place for that option is (menu vs GUI element).

**Comment by sunws4me** [comment]
yes, just remove the data from existing graph(s).  kind of need two opens, clear only 1 particular graph or all.  leave all existing points as is, just erase current line(s)

**Comment by jmthomas** [comment]
Note you can already right-click an item in the legend and delete it

**Comment by sunws4me** [comment]
looking for an easy way to get from this:
![image](https://github.com/user-attachments/assets/a00c5073-ad65-49a9-ba0f-b29024c7c06e)
to this:
![image](https://github.com/user-attachments/assets/7850f5eb-abc9-4e25-a940-c155c52aecb7)

with just a single click

the mnemonic was hidden to protect the innocent :)

**Comment by jmthomas** [comment]
Agreed, we will implement a clear data option

**Comment by sunws4me** [comment]
thx

**Comment by jmthomas** [comment]
In the PR I added the ability to right click and item and clear just its data. Or in the TlmGrapher Graph menu you have the option to clear ALL data from all items on all graphs.
