### ISSUE TITLE
script api should return success/failure in addition to existing return values

### ISSUE THREAD

**Issue by hockersmithjr** [OpenC3/cosmos#1437]
Script api should return success/failure in addition to existing return values in order to allow more custom capabilities.  check_expression, check_tolerance, etc does not return the success/failure preventing any custom logic to be applied within the test scripts.

**Comment by jmthomas** [comment]
Any of the check methods (check_expression, check_tolerance) raise if they fail. So the script will stop at that point. You can begin rescue if you want to manually handle the exception.

**Comment by hockersmithjr** [comment]
OK.  I think that will work.
