### ISSUE TITLE
A "Getting Started" sample Target Python script

### ISSUE THREAD

**Issue by rcruzmar** [OpenC3/cosmos#1442]
I am pretty new to Cosmos, and I like it a lot.  I have a Python project which generates large amounts of data and I'd like to display the information as "telemetry" in Cosmos. I already created the basic, default Plugin / Target / Interface as per the Getting Started documentation.

What I am not sure is what does the actual Python need to look like in order to communicate with Cosmos?  I have the 8080 and 8081 ports open and accessible in the Ubuntu firewall. I also build a small test Python script which allows Cosmos to connect and send a command (manually) to it.  I just do not know if this is the correct way to do this.

I just can't find the documentation to help me build a proper interface and I'd be grateful if someone could point me if someone could point me in the right direction. 

Thank you!

**Comment by jmthomas** [comment]
COSMOS can connect to anything and speak any protocol. Start with the [Burst protocol](https://docs.openc3.com/docs/configuration/protocols#burst-protocol) which will just read anything you throw at it and put it into a packet. But ultimately you need a protocol which can support Packet delineation. The most common is the [Length protocol](https://docs.openc3.com/docs/configuration/protocols#length-protocol). Length basically means you're sending a bunch of data to COSMOS with a length field to tell how much data to read. Then you start filling in your packet definitions using the [Telemetry Configuration](https://docs.openc3.com/docs/configuration/telemetry).

**Comment by jmthomas** [comment]
COSMOS is meant to connect to existing data sources in targets (either SW or HW). If you already have a socket just configure the interface to talk to that socket and you should see raw data. If you're trying to build a "fake" data source for testing then I guess that works as well.
