### ISSUE TITLE
type-to-search, dropdown

### ISSUE THREAD

**Issue by KV4S2** [OpenC3/cosmos#1450]
in many openc3 text-dropdowns, one can type characters which will then highlight matching substrings within the dropdown possibilities.  how does one enter multiple sets of characters, or multiple search substrings.  this will then quickly allow selection from the dropdown options, since with two or more substrings the exact match probability goes up vastly..

thanks

**Comment by jmthomas** [comment]
Our drop downs do not support multiple fields for search. We currently have ticket https://github.com/OpenC3/cosmos/issues/964 to support searching all the items in a target (vs first choosing a target and packet).
