### ISSUE TITLE
Data Extractor does not capture BLOCK in a useful manner

### ISSUE THREAD

**Issue by timothyscherer** [OpenC3/cosmos#1452]
I am trying to capture many raw packets using the data extractor, the contents of which are large binary chunks. When I do so, the data field simply says "BINARY", which is not useful at all. I tried using both CONVERTED, RAW, and FORMATTED formats, with the same result each time.

![image](https://github.com/user-attachments/assets/4cf7b383-2e79-462c-b312-a3a4161c9a7c)

I would like the field column to contain the data represented as a hex string, or something else that actually conveys the content. I'm not particular about the format.

Alternatively, a means to download all packets in the data viewer would work - as it is right now, you can only download the packet you are looking at.

**Comment by jmthomas** [comment]
I think we could support outputting binary as a hex string. The danger is that you try to export a huge binary field but that'll be on the user to properly configure their output.
