### ISSUE TITLE
Show remaining time to wait when in wait state in script runner

### ISSUE THREAD

**Issue by 321github123** [OpenC3/cosmos#1457]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Is your feature request related to a problem? Please describe.**
It is unclear how much time is remaining during a wait check.

**Describe the solution you'd like**
A countdown box shows the remaining time to wait if the script is in a waiting state.

**Additional context**

![image](https://github.com/user-attachments/assets/2d9ea0b7-f01f-4fb5-a742-e315816a02c1)

**Comment by jmthomas** [comment]
This could probably just be added in the Script State box. Something like `Waiting 5` ... `Waiting 4` ... `Waiting 3` ... etc
