### ISSUE TITLE
Add ability to log selected telemetry value

### ISSUE THREAD

**Issue by 321github123** [OpenC3/cosmos#1458]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Is your feature request related to a problem? Please describe.**
We would like the ability to log a telemetry value over time

**Describe the solution you'd like**
User can select a telemetry item and a time (either received time or packet time).  UI would show the telemetry values (in text) over time.

User can add multiple telemetry item (in different tabs)

User can stop the logging.

User can configure logging frequency

User can export the log to file.

**Additional context**

![image](https://github.com/user-attachments/assets/445c0c86-ad75-4278-9dd2-dc6ad1c77b6b)

![image](https://github.com/user-attachments/assets/a0e64188-827e-49fd-a24d-59c011ffb107)

![image](https://github.com/user-attachments/assets/2c2df988-3c99-409b-8f66-5112e3c4d1b5)

**Comment by sunws4me** [comment]
single tab could include multiple telemetry points as well.

**Comment by jmthomas** [comment]
This would probably be best implemented as a Data Viewer widget. It allows you to output an arbitrary number of items but currently it is printing out the entire packet. We would just have to create a new widget to display an individual item with the associated timestamp

**Comment by jmthomas** [comment]
Note this type of DataVIewer widget would also work well for JPL FPrime events which are best displayed in a time series.

**Comment by 321github123** [comment]
If possible, it would be great if this new data viewer widget had the following features

* user can add arbitrary number of items -- a single text line would display selected items from a single packet
* user can filter on a selected item
* user can freeze/unfreeze the flow of displayed data
* view persists if the user changes views and comes back

**Comment by 321github123** [comment]
@jmthomas Any chance you might have a rough estimate for when your team might release this future?  A ballpark figure, if available, would help our team's planning greatly.

**Comment by 321github123** [comment]
Another feature request would be the ability add items from different packets.  Each line of the output would be values of a single received packet e.g. if user chose packet_A.item_1, packet_A,item_2, and packet_B.item_1, the output would look like the following

```
time_1 packet_A.item_1 packet_A.item_2
time_2                                                     packet_B.item_1
time_3 packet_A.item_1 packet_A.item_2
time_4 packet_A.item_1 packet_A.item_2
```
There could also be an option (a toggle?) to propagate forward other packets values e.g.


time_1 packet_A.item_1 packet_A.item_2
time_2 (same as above) (same as above)  packet_B.item_1
time_3 packet_A.item_1 packet_A.item_2 (same as above) 
time_4 packet_A.item_1 packet_A.item_2 (same as above) 
```

**Comment by jmthomas** [comment]
@321github123 this might not make the September release but I plan on having it done by the October release. It's a little more involved than I thought because DataViewer is currently Packet oriented and this is all item oriented. It's all possible but a little more frontend work than I thought. :-)

**Comment by 321github123** [comment]
Very helpful - thanks much!
