### ISSUE TITLE
Imageviewer Formats?

### ISSUE THREAD

**Issue by nickAtomosSpace** [OpenC3/cosmos#1459]
Hopefully a quick question/answer. I am interested in making use of the Imageviewer widget. I see a list of formats "Format | The image format of the base64 data (e.g. jpg, png, etc)" What all formats are available/supported?

Thank you!

**Comment by nickAtomosSpace** [comment]
A follow on question, there isn't a flavor/ability of Imageviewer without base64 encoding?

**Comment by jmthomas** [comment]
We support any of the image mime types as defined: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#image. You do have to be base64 encoded so we can display it inline.
