### ISSUE TITLE
Restrict command parameters to configured states

### ISSUE THREAD

**Issue by 321github123** [OpenC3/cosmos#1471]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Is your feature request related to a problem? Please describe.**
For a command parameter that has a set of states (i.e. an enumeration), would it be possible to restrict the user to only sending a parameter that is one of the states?

**Describe the solution you'd like**
The user cannot set a value via MANUALLY_ENTERED that is not a valid state.

**Additional context**
![image](https://github.com/user-attachments/assets/a9b88042-87c6-4d3a-ae7d-7e031382c261)

Cosmos allows the manually entering of a non-valid state, e.g., 777, and the sending the command with this parameter.

**Comment by jmthomas** [comment]
If we're talking just about Command Sender then I think that's reasonable. We'll always allow the user to override the command parameter in a script because that's really useful for edge case testing in the UUT software.

If we disable the MANUALLY_ENTERED field in Command Sender they would still be able to go into the script output and edit it manually to send whatever.

**Comment by 321github123** [comment]
Disabling the MANUALLY_ENTERED in Command Sender sounds like a good near term solution.  Could we add a flag that enforces the state enumeration?

**Comment by ryanmelt** [comment]
We can add a RANGE_CHECK_STATES flag

**Comment by jmthomas** [comment]
We already have variations on cmd: `cmd, cmd_no_range_check, cmd_no_hazardous_check, cmd_no_checks`. It seems like this should be part of the `cmd_no_range_check` category. If you send a command with a state enumeration using `cmd` it should fail unless you use `cmd_no_range_check`. This is a pretty big breaking change though so we couldn't implement it until COSMOS 6.

**Comment by ryanmelt** [comment]
The default behavior can't change until COSMOS 6, but we could add the new feature flag before then.
