### ISSUE TITLE
Upgrade to ESLint 9

### ISSUE THREAD

**Issue by jmthomas** [OpenC3/cosmos#1479]
ESLint 9 has a new config file format called flat config we need to switch to: https://eslint.org/blog/2024/04/eslint-v9.0.0-released/

More info:
https://eslint.org/blog/2022/08/new-config-system-part-1
https://eslint.org/blog/2022/08/new-config-system-part-2

**Comment by jmthomas** [comment]
Wait until #1539 is complete

**Comment by ryan-pratt** [comment]
https://github.com/OpenC3/cosmos/pull/1722
