### ISSUE TITLE
Ingesting PCM Packets following IRIG Telemetry Standards

### ISSUE THREAD

**Issue by Tom-Frew-ELA** [OpenC3/cosmos#1482]
Hello OpenC3 COSMOS Developers! I hope you are having a good day.

My company has a lot of hardware that outputs PCM packets following the IRIG Chapter 4 and 10 telemetry standards. I am trying to design a target that can ingest such packets.

[Chapter 4](https://www.irig106.org/docs/106-11/chapter4.pdf)
[Chapter 10](https://www.irig106.org/docs/106-11/chapter10.pdf)

The structure of these packets are as follows:
<img alt="Packet Structure" src="https://github.com/user-attachments/assets/4fb15ffb-4cf6-4968-bf87-7844f208223f">

Unfortunately, the "Channel-Specific Data" (purple) section does not include the number of data segments in the body (N). How can I create a target that can accept any number of data segments?

Thanks for your time!
- Tom :)

Note: Here is my current attempt at the header of the telemetry packet.
<img alt="Nano Text" src="https://github.com/user-attachments/assets/aa544293-ebf1-4632-bc85-0e0bb0e6e727">

**Comment by jmthomas** [comment]
We just merged #1436 and #1473 to add support for multiple variable length fields in a single packet. You still need to have a length field for these variable length items so I'm not sure how that works out in the screen shot you posted. How do you know what 'n' is in the picture?

We will be releasing this support in our next release: 5.18.0.
