### ISSUE TITLE
Pin items in Packet Viewer

### ISSUE THREAD

**Issue by 321github123** [OpenC3/cosmos#1484]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Is your feature request related to a problem? Please describe.**
We would like to see the packet time of each packet (spacecraft time not received time)

**Describe the solution you'd like**
Perhaps add a field near the top of the viewer?

![image](https://github.com/user-attachments/assets/25ffe9c4-81bd-4c0f-a5ce-8e310b579651)

**Additional context**

**Comment by jmthomas** [comment]
PACKET_TIME is already included in the Derived items

**Comment by 321github123** [comment]
Would it be possible to pin a specific item then?

**Comment by jmthomas** [comment]
We could add a little pin icon on mouseover of a row and it would anchor the item to the top of the list. Pinning items would not be affected by the search so you could pin `PACKET_TIME` and then search for `TEMP` and it would show `PACKET_TIME` at the top along with `TEMP1`, `TEMP2`, etc.

**Comment by 321github123** [comment]
The pin icon would be a nice enhancement!
