### ISSUE TITLE
Can a Python script determine if it has been loaded with load_utility?

### ISSUE THREAD

**Issue by jacobian-m** [OpenC3/cosmos#1485]
Is there a built-in or OpenC3-recommended way for a Python script to check whether it has been loaded through `load_utility()`?

(Context) I need to incorporate the equivalent to an `if __name__ == '__main__'` guard in Script Runner.  However, in Script Runner, `__name__` is `running_script` whether the script has been started directly or called through load_utility.  I can't `import` the code because it needs to be instrumented.  I can get around this, but a built-in COSMOS solution would be better if it exists already.

Thanks for your work on this project and any help you can provide.

**Comment by jmthomas** [comment]
You can check for `RunningScript.instance`

**Comment by mkalin2** [comment]
That seems to work! Thanks!
