### ISSUE TITLE
File upload sometimes fails using open_file_dialog

### ISSUE THREAD

**Issue by thomasstjeangenevatech** [OpenC3/cosmos#1487]
**Describe the bug**
Occasionally, file uploads will fail when using the `open_file_dialog` method, with the error `HTTPClientException : 404 Not Found`. I believe is somehow caused by the dialog becoming "unlinked" from the code, as it is accompanied by this message upon hitting cancel: `INFO: Unexpectedly received answer for unknown prompt .`.

**To Reproduce**

Not sure of the exact reproducibility as it does not happen every time, but:
1. Create script with `upload_file_dialog` method
2. Upload file
3. File upload fails

**Expected behavior**
File should upload successfully every time.

**Screenshots**
![image](https://github.com/user-attachments/assets/bc5235fd-b509-4838-9475-47a162528b73)
![image](https://github.com/user-attachments/assets/10a1fe70-dc6c-43e6-a34e-583362d0d1a4)

**Environment (please complete the following information):**

- OS: Windows 11, COSMOS server running on Ubuntu 22.04.1
- OpenC3 COSMOS Version: 5.17.1
- Browser: Chrome and Firefox

**Comment by jmthomas** [comment]
I was able to reproduce. Thanks for the report.
