### ISSUE TITLE
Enumerations On Telemetry/Command Definitions

### ISSUE THREAD

**Issue by lorenzo-gomez-windhover** [OpenC3/cosmos#1493]
Hi there,

What is the recommended COSMOS way of generating enumerated data inside Telemetry/Command ASCII files?

I understand that, in terms of encoding, enumerations are just integers, but I'm just wondering if COSMOS has a mechanism for presenting enumerations in a more user-friendly manner?

I looked up this topic in the documentation and github issues, but nothing came up. I'm new to COSMOS, so I apologize in advance if this seems like an obvious/silly question.

Thanks

**Comment by lorenzo-gomez-windhover** [comment]
I should also note; I did find mention of enumerated types for XTCE. However given the fact that ASCII files are the first-class citizens in COSMOS, we decided to use the COSMOS ASCII format.

**Comment by jmthomas** [comment]
We call these [STATE](https://docs.openc3.com/docs/configuration/command#state) in commands and [STATE](https://docs.openc3.com/docs/configuration/telemetry#state) in telemetry.

**Comment by lorenzo-gomez-windhover** [comment]
Thanks :+1:
