### ISSUE TITLE
RECEIVED_COUNT on a packet which has never been received should return 0 not nil/null

### ISSUE THREAD

**Issue by kearneylackas** [OpenC3/cosmos#1494]
If a packet has never been received, the received count value currently is null or nil. It would be more intuitive for this value to report 0.

In my case, I have a NAK packet that is returned for a variety of commanding errors. I want to verify that is zero.
```
# Verify NAK is zero. This doesn't work.
check("UUT NAK RECEIVED_COUNT == 0")

# Verify NAK is zero. This DOES work but is less readable.
check_expression("tlm('UUT NAK RECEIVED_COUNT').nil?")
```

Tested on COSMOS 5.18.0 in Chrome

**Comment by jmthomas** [comment]
Our general philosophy is to set things that haven't been receive to `None` (python) or `nil` (Ruby) to indicate that they have never been received. 0 obviously could be a valid value for some telemetry. However, the `RECEIVED_COUNT` is a derived items which I agree makes more sense to default to 0. We'll see how difficult it would be to implement this default.
