### ISSUE TITLE
Horizontal scroll bar for Telemetry Viewer

### ISSUE THREAD

**Issue by 321github123** [OpenC3/cosmos#1509]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Is your feature request related to a problem? Please describe.**
If we build a screen that is wide, there does not appear to be way to scroll horizontally left and right.  We are currently zooming out to see the entire screen.

**Describe the solution you'd like**
If this screen is wide, a horizontal scroll bar becomes available.

**Additional context**

**Comment by jmthomas** [comment]
@321github123 TlmGrapher automatically scales the graph according to the display size. I'm not sure what you're looking for here.

**Comment by ryanmelt** [comment]
I think TlmViewer was meant.

**Comment by 321github123** [comment]
Yes sorry I meant TlmViewer  -- thanks for the correction Ryan!  When we have many screens side by side, we are not able to scroll horizontally
