### ISSUE TITLE
Ability to sort telemetry item alphabetically in Packet Viewer

### ISSUE THREAD

**Issue by 321github123** [OpenC3/cosmos#1514]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Is your feature request related to a problem? Please describe.**
User would like to see all telemetry items of a packet in alphabetical order.

**Describe the solution you'd like**
User has ability to sort displayed telemetry item in Packet Viewer either alphabetically or by bit order (which appears to be current behavior)

**Additional context**

**Comment by jmthomas** [comment]
Simply click the 'Name' header:
<img width="1026" alt="Screenshot 2024-09-05 at 10 12 20 AM" src="https://github.com/user-attachments/assets/e3d4a0db-4fb1-4156-abd9-3df69af8de24">
