### ISSUE TITLE
After sorting by name in Packet Viewer, how to switch back to the default byte ordering of items?

### ISSUE THREAD

**Issue by 321github123** [OpenC3/cosmos#1515]
If a user sorts by name in Packet Viewer, how does the user switch back to sorting by byte ordering of items (the default view)?

**Comment by jmthomas** [comment]
Clicking Name sorts ascending, clicking again sorts descending, clicking again goes back to sort by byte ordering.

**Comment by jmthomas** [comment]
re #1514
