### ISSUE TITLE
open_files_dialog as operator (Enterprise)

### ISSUE THREAD

**Issue by Lakshmi5785-dev** [OpenC3/cosmos#1531]
<img width="573" alt="image" src="https://github.com/user-attachments/assets/4e6a55db-6cad-4aed-9d1e-a339c469ba41">
I tried to use the open_file_dialog and open_files_dialog as mentioned in the documentation. But both of them didn't work. For the open_files_dialog I am getting the list as empty whether I select a single file or multilple.
For the open_file_dialog Its throwing a syntax error.
<img width="678" alt="image" src="https://github.com/user-attachments/assets/d7bceaba-263f-49b6-af90-f3c17d9d7fb9">

**Comment by jmthomas** [comment]
In COSMOS Open Source everything worked as expected.

In COSMOS Enterprise I was able to successfully open files but only as Admin (we will get that fixed in a future release). Can you identify the user you were using? Can you try as Admin?

**Comment by Lakshmi5785-dev** [comment]
I am on a free license Thomas.

**Comment by jmthomas** [comment]
I can not reproduce on COSMOS Open Source 5.18.0
