### ISSUE TITLE
Referencing a script in another plug-in (gem file)

### ISSUE THREAD

**Issue by hmaclachlan** [OpenC3/cosmos#1545]
Is it possible to reference a script from another plugin (gem file) when writing scripts in a different plugin?

Ie. Say I have 2 gems:
Gem1
|__ cmd_tlm
|__ lib
|__ procedures
     |__ power_on.rb
     |__ power_off.rb
|__ screens

Gem2
|__ cmd_tlm
|__ lib
|__ procedures
     |__ test1.rb
     |__ test2.rb
|__ screens

When scripting the test2.rb, I am trying to reference power_on.rb from Gem1. I tried requiring it with this line:

require_relative '../../Gem1/procedures/power_on.rb

I am getting an error "cannot load such file." Is it possible to reference scripts in between gems or can you only reference within the current working gem in COSMOS?

**Comment by jmthomas** [comment]
Did you try referencing from the target path:
```
require 'GEM1/procedures/power_on' # Test requiring files from buckets in suite analysis
```
Note that targets must be all caps in COSMOS.
