### ISSUE TITLE
Need file paths in the script runner container

### ISSUE THREAD

**Issue by Lakshmi5785-dev** [OpenC3/cosmos#1563]
Here is the scenario
1. I have a file called test.txt and pushed it into my procedures which is available in the scriptrunner
2. Now in another script I wanted to access test.txt and get the size of the file
In C4 we used to give the path directly like 
 __dir__ = os.path.dirname(os.path.abspath(__file__))
FILE_PATH = __dir__ + "test.txt'

But in C5 as  I am not sure where exactly this file is sitting in the container, I don't know how to do this.
I have verified /src/scripts but no luck
And in the /plugins/DEFAULT/targets_modified/.. only the modified files are being copied.
can you help me where can I find my files inside script runner.(Absolute path)

**Comment by ryanmelt** [comment]
If you are dealing with files, use the get_target_file, put_target_file APIs.  Don't rely on the script container file system.
