### ISSUE TITLE
load_utility not working in 5.18

### ISSUE THREAD

**Issue by Lakshmi5785-dev** [OpenC3/cosmos#1575]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

Next search the issues here on Github. If you come up empty please submit an issue.
![image](https://github.com/user-attachments/assets/e1206252-faca-4aea-af04-0013ba233a32)

this works fine when we have a plain test, it fails when we add 
the below lines to the py file 

class TestSuite(Suite):
  def __init__(self):
      self.add_group(PING_TEST)

  def setup(self):
      # Run when Suite Setup button is pressed
      # Run before all groups when Suite Start is pressed
      pass

  def teardown(self):
      # Run when Suite Teardown button is pressed
      # Run after all groups when Suite Start is pressed
      pass

My scripts are working fine in 5.16 but are failing in 5.18

**Comment by jmthomas** [comment]
The initialization routine in python is `def __init__(self)` not `def init(self)`. Can you try changing to `__init__` and see if that fixes it?

**Comment by Lakshmi5785-dev** [comment]
I am sorry its a typo, I actually used __init__, but still i have the same error.
class TestSuite(Suite):
  def __init__(self):
      self.add_group(PING_TEST)

  def setup(self):
      # Run when Suite Setup button is pressed
      # Run before all groups when Suite Start is pressed
      pass

  def teardown(self):
      # Run when Suite Teardown button is pressed
      # Run after all groups when Suite Start is pressed
      pass

**Comment by jmthomas** [comment]
Can you post your full script? The example isn't runnable.

**Comment by Lakshmi5785-dev** [comment]
I tried ur my_test_suite.py , it works fine :(. I need to debug my script.
Thank you for the reply I am closing this ticket.

**Comment by jmthomas** [comment]
Also note that you can use File -> New Suite -> Python to generate the scaffolding for you.
<img width="539" alt="Screenshot 2024-09-26 at 10 10 29 AM" src="https://github.com/user-attachments/assets/e5c00b30-8782-4a37-bc32-294746c5dec4">

**Comment by Lakshmi5785-dev** [comment]
Yes, this is there in 5.16 as well right. By the way any idea when the above error occurs? I am unable to figure out the issue everything looks fine :(

**Comment by ryanmelt** [comment]
You'll need to provide the complete script

**Comment by Lakshmi5785-dev** [comment]
Hey Ryan, I am sorry I may not be able to share the full script. But below are few more details...
I am on v5.18.0
and this error is coming from the below file 
openc3/python/openc3/script/api_shared.py
![image](https://github.com/user-attachments/assets/781f4902-05b3-49fa-8dd5-4cc3a4c1045d)
May I know when this error raises?

**Comment by jmthomas** [comment]
That code is overridden by [`running_script.py`](https://github.com/OpenC3/cosmos/blob/1f6f7c432d81ee83e7c4ac9c15ed9110e274cada/openc3-cosmos-script-runner-api/scripts/running_script.py#L1328). Thus if you're running outside of Script Runner you will get that error.

It looks like you're getting in during the suite analysis stage which happens before it's loaded in Script Runner. I tried a bunch of things but couldn't reproduce. I'd recommend starting with the File->New Suite->Python and then slowly copying your stuff into that structure to see if you can figure out what is causing it.

**Comment by Lakshmi5785-dev** [comment]
Sure Thomas will try this out. This was working fine in 5.16. Looks line many new features added in 5.18
I was facing other issues as well. Will post them as well. All these suites worked fine in 5.16 :(

**Comment by Lakshmi5785-dev** [comment]
Suite +load_utility combination might be the issue.
I am trying to debug from run_suite_analysis.py.
Unfortunately I am unable to use print , is there a way to log messages ?

**Comment by Lakshmi5785-dev** [comment]
When I try to save the file in the script runner by keys ctrl+s it is trying to save the file in my local computer instead of saving in the script runner. I believe this is the new feature added.Is this causing the issue?
But when I tried my_script_suite.py in the demo INST2 it is just saving in the script runner container.

**Comment by jmthomas** [comment]
We try to override the ctrl+s or command+s (Mac) to save the file. This seems to work well in Chromium browsers. What browser are you using?

In any case, the Save behavior should have no effect on what you're trying to do. Without a full script I don't think we'll be able to help you any further.
