### ISSUE TITLE
Scaling/Navigation Screens Options

### ISSUE THREAD

**Issue by lorenzo-gomez-windhover** [OpenC3/cosmos#1603]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

Hi there,

I'm currently writing screens for CFS apps(cfe_es, cfe_evs, etc). As I add more screens, the "SELECT SCREEN" dropdown just keeps growing and growing.  I'd really like for all these screens to have cohesive navigation without having to scroll through an endless dropdown to fish for the screen that I want. In an ideal scenario I would like to have a button inside a screen that that opens  up another screen. For example; Main Screen-> Click on "CFE_EVS" button-> Show CFE_EVS screen. Or can screens be at least partitioned into different sets (is this what the SCOPE is for in COSMOS)? The fundamental issue is that we will potentially have 100s of screens and we need to be able to navigate those smoothly from screen to screen without having a huge dropdown where we have to fish for what we are looking for.

I guess what I am asking is what is the best way(or the COSMOS way) of scaling COSMOS to have hundreds of screens that are easy to navigate for users?

Hope the question makes sense.

Thanks
Lorenzo

**Comment by jmthomas** [comment]
The screens are organized by target and both the target and screen boxes are autocomplete enabled ... simply start typing a few letters and it will open the screen that matches.

You can also create screens that open other screens which our demo does:
```
SCREEN AUTO AUTO 1

TITLE 'Screen Launcher'
HORIZONTAL
  BUTTON 'HS' "screen.open('INST', 'HS')"
  BUTTON 'CMD' "screen.open('INST', 'COMMANDING')"
  BUTTON 'GROUND' "screen.open('INST', 'GROUND')"
END
BUTTON 'Close HS & CMD' "screen.close('INST', 'HS');; screen.close('INST', 'COMMANDING')"
BUTTON 'Close All' "screen.closeAll()" # including this screen!
```

**Comment by lorenzo-gomez-windhover** [comment]
Ah I see. Thanks! Hadn't looked closely at the examples there.
