### ISSUE TITLE
Best Way To Handle Nested Structs

### ISSUE THREAD

**Issue by lorenzo-gomez-windhover** [OpenC3/cosmos#1617]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

Hello again,

Suppose we have the following struct:

```
typedef struct CFE_TIME_ToneDataCmd_Payload
{
    CFE_TIME_SysTime_t         AtToneMET;         /**< \brief MET at time of tone */
    CFE_TIME_SysTime_t         AtToneSTCF;        /**< \brief STCF at time of tone */
} CFE_TIME_ToneDataCmd_Payload_t;
```

As you can see the first two fields have the same type, "CFE_TIME_SysTime_t". As far as I can tell COSMOS ASCII TLM/CMD format does not support "structs/aggregates", which is supported by other formats such as XTCE. Please correct me if I'm wrong on this. If that's the case, then is the only option to handle duplicate field names like in this case(Seconds and Subseconds) is to prefix those fields with the "parent". For example, in this case, I was thinking about doing something like this:

```
COMMAND CFS CFE_TIME_ToneData BIG_ENDIAN "Placeholder"
APPEND_ID_PARAMETER STREAM_ID 16 UINT 6240 6240 6240 "Packet Identification"
APPEND_PARAMETER SEQUENCE 16 UINT MIN_UINT16 MAX_UINT16 0xC000 "Sequence count" 
APPEND_PARAMETER PKT_LEN 16 UINT 21 21 21 "Packet length" 
APPEND_PARAMETER CMD_ID 8 UINT 0 0 0 "Command code" 
APPEND_PARAMETER CHECKSUM 8 UINT MIN_UINT8 MAX_UINT8 MIN_UINT8 "" 
APPEND_PARAMETER AtToneMET_Seconds 32 UINT MIN_UINT32 MAX_UINT32 MAX_UINT32 "Command Error Counter:"  "LITTLE_ENDIAN" 
APPEND_PARAMETER AtToneMET_Subseconds 32 UINT MIN_UINT32 MAX_UINT32 MAX_UINT32 "Command Error Counter:"  "LITTLE_ENDIAN" 
APPEND_PARAMETER AtToneSTCF_Seconds 32 UINT MIN_UINT32 MAX_UINT32 MAX_UINT32 "Command Error Counter:"  "LITTLE_ENDIAN" 
APPEND_PARAMETER AtToneSTCF_Subseconds 32 UINT MIN_UINT32 MAX_UINT32 MAX_UINT32 "Command Error Counter:"  "LITTLE_ENDIAN" 
```

Am I correct on this? I want to make sure I don't go down the wrong path if there is any other/better ways of doing this on COSMOS.

Thanks
Lorenzo

**Comment by ryanmelt** [comment]
There is a newer method to have structures within packets that isn't fully supported in all our tools yet.  It works well with ScriptRunner though.

It involves creating packets marked VIRTUAL and then referencing them with a conversion: https://github.com/OpenC3/cosmos/blob/main/openc3/lib/openc3/conversions/object_read_conversion.rb

Using this method you can effectively define packets within packets.   

In general though, it is better to just flatten structures and give each item within a unique name.
