### ISSUE TITLE
Best way to to stop a script execution from the script?

### ISSUE THREAD

**Issue by mkalin2** [OpenC3/cosmos#1619]
I have a script that I would like to stop running if a check fails. If I raise an exception or try sys.exit() the user can hit go again and the script will continue running.

Is there a way to make the script hit the stop button?

**Comment by jmthomas** [comment]
Try this: `raise OpenC3::StopScript`

**Comment by mkalin2** [comment]
I am using python so I did `raise StopScript` and that worked. Thanks!
