### ISSUE TITLE
Help with installing 5.19.0

### ISSUE THREAD

**Issue by bradenvirdellgenevatech** [OpenC3/cosmos#1620]
Trying to install 5.19.0 and keep running into this after I do a `./openc3.sh run`. 
![image](https://github.com/user-attachments/assets/4be3137c-8901-496f-9f2c-63b32bfc894e)

Any suggestions?
Thanks Braden

**Comment by ryanmelt** [comment]
That syntax has been used since COSMOS 5.13.0.

Are you running a really old version of docker compose?

**Comment by bradenvirdellgenevatech** [comment]
That seems to have been the issue, we are back working. Thank you
