### ISSUE TITLE
ROUTER: Add ability to specify a set of messages to route.

### ISSUE THREAD

**Issue by hockersmithjr** [OpenC3/cosmos#1625]
Add ability to specify a set of messages to route in the plugin.txt and have the router only send/receive those messages.  This would reduce the need for custom code in order to route specific messages to an endpoint that only cares about certain messages.

**Comment by jmthomas** [comment]
We already have an [ignore_packet_protocol](https://docs.openc3.com/docs/configuration/protocols#ignore-packet-protocol) that allows you to ignore certain "messages" (we call them packets).

**Comment by ryanmelt** [comment]
You can attach protocols to routers (just like interfaces) to do things like filtering.  As Jason pointed out the ignore_packet_protocol should already do what you are asking for

**Comment by hockersmithjr** [comment]
Thanks.  I will give it a try.
