### ISSUE TITLE
Using RECIEVED_TIMESECONDS to detect stale telemetry

### ISSUE THREAD

**Issue by hmaclachlan** [OpenC3/cosmos#1628]
Is RECIEVED_TIMESECONDS a date object or an integer? In https://docs.openc3.com/docs/configuration/telemetry it denotes it is a date/time object, while in https://docs.openc3.com/docs/configuration/telemetry-screens#:~:text=Items%20from%20packets%20with%20RECEIVED_TIMESECONDS%20greater%20than%20this,avoid%20false%20positives%20due%20to%20race%20conditions.%20True under STALE_TIME it describes RECEIVED_TIMESECONDS as a field that can be compared to STALE_TIME (which is an integer - number of seconds). 

I am trying to detect if telemetry from a target is stale. I want "if stale, then run this command, else exit":

if TARGET TELEMETRY RECEIVED_TIMESECONDS > 30
        cmd(...)
else
        exit
end

Is this the correct usage of RECIEVED_ TIMESECONDS? Or would the if statement need to be:
if TARGET TELEMETRY RECEIVED_TIMESECONDS < Time.now - 30

**Comment by jmthomas** [comment]
You can do something like this (if you're dealing with 1Hz tlm for example):
```
if (Time.now.to_f - tlm("INST HEALTH_STATUS RECEIVED_TIMESECONDS") > 5)
  puts "STALE"
else
  puts "CURRENT"
end
```

RECEIVED_TIMESECONDS is a number when requested in telemetry. Internally in the Packet object it is a date/time but that's an implementation detail (which actually may change) that you don't need to worry about.
