### ISSUE TITLE
Bucket Explorer: Go to the Base Directory when Clicking the Buckets or Volumes Buttons

### ISSUE THREAD

**Issue by stephen-ritter** [OpenC3/cosmos#1678]
When using the Bucket Explorer, it would be nice when one clicks on the Buckets or Volumes buttons to be redirected to the base directory for that bucket or volume. Right now if you are already in the bucket or volume and you click the button for the same location it does nothing.
![image](https://github.com/user-attachments/assets/50ea8473-888d-482b-9d23-a37a52f55964)

**Comment by jmthomas** [comment]
closed by #1539
