### ISSUE TITLE
Telemetry Viewer: Large Telemetry Screens Go Off the Screen

### ISSUE THREAD

**Issue by stephen-ritter** [OpenC3/cosmos#1681]
Large telemetry screens will end up going off the screen without a clean way of accessing the information that is off screen. I realize this is more on the user making the screens to make a more compact screen, but I was wondering if a way to scroll to the space that is off screen could be implemented. It is somewhat difficult to close the screens as well when they go off screen, since the close button is on the top right of the window. I know you can float the screen and move it to the left to get access to it, but if you have a lot of screens already displayed it will collapse all the other screens onto the floating screen. I wonder if having the Telemetry Viewer auto scale based on the size of the screen would help here?
![screen](https://github.com/user-attachments/assets/bfd6b87c-327e-4a74-b037-1295c6e038f7)

**Comment by jmthomas** [comment]
We recently implement horizontal scrolling in applications which I believe addresses this issue: https://github.com/OpenC3/cosmos/pull/1639
