### ISSUE TITLE
DERIVED inadequately documented

### ISSUE THREAD

**Issue by pprindeville** [OpenC3/cosmos#1691]
**Describe the bug**
The documentation on `DERIVED` mentions constraints on it, but not its usage.

**To Reproduce**

1. Go to https://ballaerospace.github.io/cosmos-website/docs/v4/telemetry#telemetry-definition-files
2. Read the details on `DERIVED`.

**Expected behavior**
An explanation of the intended usage of `DERIVED` should be given.

Also, it's stated:

> If Bit Offset is 0 and Bit Size is 0 then this is a derived parameter and the Data Type must be set to `‘DERIVED’`.

Does the reverse also apply?  Must `DERIVED` always have an offset and size of zero?

**Screenshots**
N/A

**Environment (please complete the following information):**

N/A

**Comment by ryanmelt** [comment]
Current docs are here: https://docs.openc3.com/docs/configuration/telemetry#derived-items
Which seem ok.   Not sure why you are referencing the old cosmos 4 docs.
