### ISSUE TITLE
How to check the connection status of a target in a script

### ISSUE THREAD

**Issue by hmaclachlan** [OpenC3/cosmos#1706]
Hello, 

Is there a method to checking the connection status of a target in a script? In digging through the code of the CmdTlmServer, it seems as though you can use item.connected to determine connection status, I am unsure how to configure to be used in script runner. 

![image](https://github.com/user-attachments/assets/fe7e93dd-f7d3-406d-af93-da5de52d9aa5)

Thanks

**Comment by jmthomas** [comment]
See https://docs.openc3.com/docs/guides/scripting-api#interfaces
```
interface = get_interface("INST_INT")
puts interface['state']
```
