### ISSUE TITLE
Is there documentation for hooking up the monitoring to Datadog? 

### ISSUE THREAD

**Issue by badrobit** [OpenC3/cosmos#1750]
I had checked out [this page in the documentation](https://docs.openc3.com/docs/guides/monitoring), but I wasn't getting many of the answers I expected tas I have seen with other integrations. I was hoping you might have some "unofficial" documentation using [Datadog](https://docs.datadoghq.com/agent/?tab=Linux) or an [open-telemetry](https://opentelemetry.io/) compliant agent to allow for distributed monitoring.

**Comment by ryanmelt** [comment]
COSMOS supports open telemetry already (though I haven't tested it for awhile).
You need to set these two environment variables on the containers that you want to use with open telemetry:

OTEL_EXPORTER_OTLP_ENDPOINT=your endpoint url
OPENC3_OTEL=ALL

Note that using open telemetry is not side effect free and hurts performance

**Comment by badrobit** [comment]
Would you happen to know what the level of impact is? I fully expected there to be some impact, but I'm curious if any profiling has been done so we could determine whether it is worth deploying.

**Comment by ryanmelt** [comment]
Its not horrible, I would say just try it.  
I don't recommend leaving it on all the time though, generally just for debugging things like overall performance.
