### ISSUE TITLE
CHECKBUTTON manipulation, and default values

### ISSUE THREAD

**Issue by mountTom** [OpenC3/cosmos#1753]
I am porting over COSMOS 4 code to COSMOS 5, and have seem to run into two issues with CHECKBUTTONS.

The first is the default CHECKBUTTON STATE. In COSMOS 4, and what  I can tell in the early documentation of COSMOS 5, you were able to define the initial state of a checkbutton.

`NAMED_WIDGET ENABLE CHECKBUTTON 'ENABLE?' 'CHECKED'`

Has this been removed, or is there a new way of doing this?

Secondly, I often had 5+ of these check buttons, followed by a "SELECT ALL" . The select all would reverse the common "get_named_widget" to enable all check buttons. 

`BUTTON 'Select All'         'screen.get_named_widget("ENABLE").checked() = 1;'`

Has sytax for this changed aswell, and If so, where could I find the new functions to use?

**Comment by jmthomas** [comment]
It looks like the optional `CHECKED` parameter got removed. I can add that back in an upcoming release.

Programmatically changing the value would require you to do `screen.get_named_widget("ENABLE").value = true`
