### ISSUE TITLE
TlmGrapher can't fit two graphs horizontally when shrunk

### ISSUE THREAD

**Issue by ryanmelt** [OpenC3/cosmos#1767]
Should be able to fit 4 total graphs on the same screen when in most shrunk mode

**Comment by ryan-pratt** [comment]
This was fixed in https://github.com/OpenC3/cosmos/pull/1757/commits/5aad83f56b8161578b9edd7d40b6f4d6ad40b921
![image](https://github.com/user-attachments/assets/89345ebf-9c8d-4286-b217-003b8b0dccbc)
