### ISSUE TITLE
Spawn script as background script

### ISSUE THREAD

**Issue by jmthomas** [OpenC3/cosmos#186]
Script Runner API method to spawn a script in the background

**Comment by MTI-twalker** [comment]
How is this different than a microservice?

Would it be possible to instead have the admin->microservice tab have start/stop buttons that can refresh running instances of microservices? 
That way you can upload your microservice plugin and control when its running.

**Comment by ryanmelt** [comment]
Microservices are long lived and kept alive by our framework, where scripts are short lived.

Being able to cycle microservices from the Admin tab would be a great feature though.

**Comment by jmthomas** [comment]
You can run a script in the background using the `script_run` API:

        script_run("INST/procedures/collect.rb")

If the script requires user input it just waits until you connect to it.

**Comment by mkalin2** [comment]
Is there a function that can stop a script that is running in the background?


I tried using `script_delete` but that didn't seem to work.

**Comment by jmthomas** [comment]
You're looking for `running_script_stop(id)`

Once we merge https://github.com/OpenC3/cosmos/pull/1803 this will all be documented

**Comment by mkalin2** [comment]
Nice! That works thanks.
