### ISSUE TITLE
Scriptable TlmGrapher for automatic plot generation 

### ISSUE THREAD

**Issue by zane-sauer** [OpenC3/cosmos#22]
I found a feature request [here](https://github.com/BallAerospace/COSMOS/issues/1701) on the COSMOS repo to make TlmGrapher load config scriptable. Have there been any updates to the feature linked previously?

**Comment by jmthomas** [comment]
TlmGrapher already can save and load a configuration. However it would be nice to make the configuration load scriptable and the configuration store the time ranges (fixed and relative, e.g. 1hr ago) so you could automate the generate of plots. Go to the TlmGrapher URL with the right parameters and autogenerate a plot which could be screenshotted and downloaded.

**Comment by jmthomas** [comment]
No additional work yet but knowing someone values this feature will bump it up on our list. :-)

**Comment by jmthomas** [comment]
We also need the ability to export graphs as images or PDFs

**Comment by ryanmelt** [comment]
This functionality is going to be supported through Grafana in a future release.  Closing this ticket.
