### ISSUE TITLE
When should we expect the next OpenC3 release?

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/cosmos#252]
Hey guys!

No rush, but we at GTI are anticipating the next release so we can take advantage of the Data Extractor and new features.

Thanks,

Dakota

**Comment by ryanmelt** [comment]
This week.  We've completed all the big changes, and are now ringing things out and closing a few more low hanging fruit issues.

**Comment by GTI-Dakota** [comment]
Cool, thanks!
