### ISSUE TITLE
Load tool configuration file with script (automatically on start-up)

### ISSUE THREAD

**Issue by KodiakLiDAR** [OpenC3/cosmos#253]
Hello OpenC3 team,

I would like to load pre-saved configuration files on OpenC3 start-up. Essentially, I'd like to be able to load saved configuration files, such as **Telemetry Grapher** configurations or **Telemetry Viewer-Telemetry Screen** configurations, using a script in _any language_.

This would allow a .sh/.bat script to launch OpenC3 and load all system relevant tool configurations on start up.

Thank you very much for any and all guidance.

Kindly,
Kodiak

**Comment by jmthomas** [comment]
Requires ticket #187 to enable local mode to store those configurations if you want to start up with that stuff loaded.

**Comment by ryanmelt** [comment]
This will be implemented with enhanced local mode #187. Closing this ticket.
