### ISSUE TITLE
HttpClientInterface and HttpServerInterface

### ISSUE THREAD

**Issue by ryanmelt** [OpenC3/cosmos#270]
Add an HttpClientInterface to support connecting to HTTP servers (like web pages, and other HTTP based apis)
Add an HttpServerInterface to support receiving Webhooks

**Comment by bradenvirdellgenevatech** [comment]
I have created an http interface in the past currently it only handles get and post requests as that is all we needed it for. I believe it could be expanded upon relatively easily. If you are interested in looking at let me know I have received permission to share it.

**Comment by ryanmelt** [comment]
Sure, you can submit a pull request or email it to us.   I'll at least use it for inspiration.  I want to do a trade between the various http clients and make sure we are still using the best one.

**Comment by HoboKennyG** [comment]
> I have created an http interface in the past currently it only handles get and post requests as that is all we needed it for. I believe it could be expanded upon relatively easily. If you are interested in looking at let me know I have received permission to share it.

Any chance you'd be willing to share with me the interface you wrote?  I'm also looking to use Cosmos to connect to a device using http get and post requests.
