### ISSUE TITLE
Guide for Creating Tools and Microservices

### ISSUE THREAD

**Issue by jeffstjean** [OpenC3/cosmos#280]
Hi all,

I am trying to get a better understanding of tools and microservices and there doesn't seem to be a ton of documentation on the website. I've tried to brute force my way through creating an COSMOS tool with little success. Is there a guide or tutorial that one can follow to create a tool or microservice?

It seems some modification has to happen to the COSMOS source to get the files uploaded to minio but I can't figure out how. I have the tool showing up of the left tab when running COSMOS but it doesn't show up in the tools directory of minio. Is there an example or guide I can follow to accomplish this?

**Comment by jmthomas** [comment]
I created issues on our website repo for this: https://github.com/OpenC3/openc3.com/issues/19, https://github.com/OpenC3/openc3.com/issues/20
