### ISSUE TITLE
Update StreamingAPI Documentation to ensure mode is part of the key

### ISSUE THREAD

**Issue by MTI-twalker** [OpenC3/cosmos#282]
Items are requested by keys of the form: 
`<CMD or TLM>__<TARGET NAME>__<PACKET NAME>__<ITEM NAME>__<VALUE TYPE>`

Now appears to be
`<MODE>__<CMD or TLM>__<TARGET NAME>__<PACKET NAME>__<ITEM NAME>__<VALUE TYPE>`

Entire packets can also be requested by keys of the form: 
`<CMD or TLM>__<TARGET NAME>__<PACKET NAME>__<VALUE TYPE>`

Now appears to be
`<MODE>__<CMD or TLM>__<TARGET NAME>__<PACKET NAME>__<VALUE TYPE>`

**Comment by jmthomas** [comment]
closed by https://github.com/OpenC3/openc3.com/pull/35
