### ISSUE TITLE
Sending a command (in a begin rescue block) to a disconnected interface now crashes the interface 

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/cosmos#301]
Hello,

Since the 5.1.0 update, gems that previously utilized microservices to poll telemetry within a begin rescue loop can no longer do so safely when an interface is disconnected. In 5.0.11, the rescue would handle a disconnected interface, but with the current build, the rescue is not handling it, and the interface crashes and must be spun up again. Thus, this creates an endless crash-restore loop as long as a particular device is not actively connected to.

![image](https://user-images.githubusercontent.com/111302074/205139975-5d57923d-6a55-47a6-a45c-bccba7306314.png)

We had stopped using the get_interface API call previously to check connected/disconnected state, but stopped using it due to server optimization reasons. Is it feasible to re-implement this API call once more in multiple microservices?

**Comment by ryanmelt** [comment]
I can't recreate this.   

```
begin
  cmd("EXAMPLE START")
rescue
  puts "Rescued"
end
```

Works as expected.   The interface prints an error but does not crash.

Is this something with a custom interface you have built?

**Comment by GTI-Dakota** [comment]
Oh, you're correct. My mistake, I had been looking at two errors, the one which was crashing the interface is not related to this issue and has been since resolved. I do see the large error in the log window.

Is there any way to suppress this error? It is quite large in the log window screen. I would expect the rescue to prevent such an error from printing, as it did in 5.0.11

**Comment by ryanmelt** [comment]
Doesn't really need to post a stack trace for an interface not connected error.  I'll clean this up in the next release.
