### ISSUE TITLE
Even when specifying OPENC3_TAG=5.1.1 in .env , the latest beta version is built (OpenC3/COSMOS repo)

### ISSUE THREAD

**Issue by jurgensymynck** [OpenC3/cosmos#303]
This is more a cautionary warning than a bug I believe...

I have to use the "OpenC3/cosmos" instead of the reccomended  "OpenC3/cosmos-project" repo, because I want to create the Ethernet To Serial bridge connection, solved and documented in several other posts at BallAerospace/COSMOS.

When cloning that repo, it's the latest beta version (in lmy case 5.1.2-beta) 
Setting OPENC3_TAG=5.1.1 does not prevent building that latest beta version. Is this the desired behavior?

I assume that i must reset the GIT "main" branch to repo to the label "5.1.1" before building OpenC3/cosmos

If this is the desired behavior, I believe it's not a bad Idea to add this to the documentation of Ethernet To Serial connection, 
(all useful issues reside at the BallAerospace/COSMOS repo I 'm afraid)

Greetings, Jurgen

**Comment by ryanmelt** [comment]
I'm going to document the bridge system probably tomorrow.  But yes, this is expected.  When are you building (using start), it will build whatever code is present and the tag is effectively ignored.  When you are running from built containers (using run), then the tag is used.   Note if you build and then run, it will run the local version which might now be mis-tagged if you changed the tag from latest before building.    

I'll probably add some better documentation on all the different cmd line options as well on a web page.
