### ISSUE TITLE
Screen files error if filename starts with capital letter

### ISSUE THREAD

**Issue by scandey** [OpenC3/cosmos#307]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**
Screen files must have lowercase file names or "Network error: HTTP 500 - Internal Server Error" occurs (no other debugging info that I could find). 

I only figured out what was happening thanks to this older issue: https://github.com/BallAerospace/COSMOS/issues/1726 

**To Reproduce**
Generate any plugin with a screen file starting with a capital letter. Plugin builds and installs fine, but when trying to open the screen, network error appears above. No messages in the CmdTlm log and I'm not sure where else to look for messages.

**Expected behavior**
Screen files should load regardless of filename. If there is an issue with formatting, errors should go in the log with all the other errors. 

**Screenshots**
<img width="1076" alt="Screen Shot 2022-12-02 at 12 52 48 PM" src="https://user-images.githubusercontent.com/1695225/205384338-01de7b87-7414-446c-a023-fe8617d304b9.png">

**Environment (please complete the following information):**

- OS: Mac OS 12.6.1
- OpenC3 COSMOS Version 5.0.11
- Browser
  -- [] Internet Explorer (IE)
  -- [x] Google Chrome
  -- [] Chromium based browsers
  -- [] Mozilla Firefox
  -- [] Safari

**Comment by jmthomas** [comment]
We're going to keep this convention of lowercase screen names because it makes discovery of the files much simpler (no searching the path). But I'll add a check in the plugin installation and validation for this and warn the user.
