### ISSUE TITLE
Data Extractor still crashing on 5.1.1

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/cosmos#314]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**
The Data Extractor still crashes the COSMOS server when used with large target/packet amount

**To Reproduce**
Open The Data Extractor Tab. Attempt to extract data from a timeset. server crashes

**Expected behavior**
Expected behavior was data extractor not crashing the server

**Environment (please complete the following information):**

- OS: Ubuntu 22.04
- OpenC3 COSMOS Version: 5.1.1
- Browser
  -- [] Internet Explorer (IE)
  -- [x] Google Chrome
  -- [x] Chromium based browsers
  -- [] Mozilla Firefox
  -- [] Safari

For more information, we have:
 - 19 Targets
 - 344 TLM Packets
 - 840 CMD Packets

**Comment by ryanmelt** [comment]
Going to need a stack trace or some more info.  What is crashing?
docker logs <cmd-tlm-api container hash>

**Comment by ryanmelt** [comment]
Any updates?
