### ISSUE TITLE
Issues with global_subsettings

### ISSUE THREAD

**Issue by bradenvirdellgenevatech** [OpenC3/cosmos#317]
So I am trying to do a GLOBAL_SUBSETTING for LABELVALUEDESC. I am able to use the SUBSETTING on individual  LABELVALUEDESC widgets but the global version doesnt seem to be working. 

I am doing it like this `GLOBAL_SUBSETTING LABELVALUEDESC 0 WIDTH 275px` from my understanding this should cause the LABEL WIDTH to be set to 275.

Am I missing something here?

**Comment by jmthomas** [comment]
That is how it is supposed to work but we're currently not applying any global subsettings.

**Comment by bradenvirdellgenevatech** [comment]
Thanks for the info I will keep an eye out for the update
