### ISSUE TITLE
File Downloading

### ISSUE THREAD

**Issue by jeffstjean** [OpenC3/cosmos#330]
**Is your feature request related to a problem? Please describe.**
I currently download files from OpenC3 by using docker commands to copy them to my local machine.

**Describe the solution you'd like**
A method for downloading files saved by scripts or protocols within OpenC3 that doesn't require knowledge of the internal file structure.

**Additional context**
There are files that are generated on-the-fly as telemetry is processed, operators should be able to navigate a list of files and download them.

**Comment by ryanmelt** [comment]
For now, the solution is to access the built-in minio console at http://localhost:2900/minio.
In the future we plan to add similar functionality that will work without whichever bucket backend you are using.
