### ISSUE TITLE
[OpenC3 COSMOS 5.1.1] Operator container communicates with Redis-Ephemeral on ports reserved for COSMOS TCP interfaces

### ISSUE THREAD

**Issue by jwestra-carrastro** [OpenC3/cosmos#340]
We are using a set of TCP server interfaces in COSMOS to log our telemetry data and send commands to targets. To support this we have exposed ports 60000-60999 to our host machine with the following lines in compose.yaml under openc3-operator:
```
ports:
 - "60000-60999:60000-60999"
```
This works fine for a while, but when we keep the container running for multiple days with the TCP server interfaces disconnected, we find that the openc3-operator container has started communicating with the openc3-redis-ephemeral container on many of these ports, and we are unable to connect our TCP server interfaces in COSMOS.

Is there a way to restrict the ports that openc3-operator uses to communicate with openc3-redis-ephemeral, in order to reserve these ports for our COSMOS targets?

**Comment by ryanmelt** [comment]
Those port ranges are in the typical ranges used by kernels for "ephemeral ports".  See: https://en.wikipedia.org/wiki/Ephemeral_port

You will have problems using them and would have to change your OS settings to not have problems.

I would recommend only using ports that are less than 32768.   20000-20999 might be a good range.
