### ISSUE TITLE
Raw mode for StreamingAPI fails (tested against V5.2.0)

### ISSUE THREAD

**Issue by MTI-twalker** [OpenC3/cosmos#344]
RAW MODE ISSUES
This occurs when requesting RAW mode with the StreamingAPI.

{"time":1669221771428859808,"@timestamp":"2022-11-23T16:42:51.428+00:00","severity":"ERROR","microservice_name":"CMD__TLM__API","container_name":"2c87dbea1f34","log":"LoggedStreamingThread unexpectedly died\nRuntimeError : System.instance parameters are required on first call\n/usr/lib/ruby/gems/3.1.0/gems/openc3-5.1.1/lib/openc3/system/system.rb:104:in `instance'\n(eval):1:in `telemetry'\n/usr/lib/ruby/gems/3.1.0/gems/openc3-5.1.1/lib/openc3/logs/packet_log_reader.rb:335:in `identify_and_define_packet_data'\n/usr/lib/ruby/gems/3.1.0/gems/openc3-5.1.1/lib/openc3/logs/packet_log_reader.rb:154:in `read'\n/usr/lib/ruby/gems/3.1.0/gems/openc3-5.1.1/lib/openc3/logs/packet_log_reader.rb:185:in `read'\n/usr/lib/ruby/gems/3.1.0/gems/openc3-5.1.1/lib/openc3/logs/packet_log_reader.rb:173:in `read'\n/usr/lib/ruby/gems/3.1.0/gems/openc3-5.1.1/lib/openc3/logs/buffered_packet_log_reader.rb:51:in `fill_buffer'\n/usr/lib/ruby/gems/3.1.0/gems/openc3-5.1.1/lib/openc3/logs/buffered_packet_log_reader.rb:35:in `next_packet_time'\n/src/app/models/streaming_object_file_reader.rb:108:in `block in next_packet_and_topic'\n/src/app/models/streaming_object_file_reader.rb:107:in `each'\n/src/app/models/streaming_object_file_reader.rb:107:in `next_packet_and_topic'\n/src/app/models/streaming_object_file_reader.rb:135:in `next_packet_and_topic'\n/src/app/models/streaming_object_file_reader.rb:60:in `read'\n/src/app/models/streaming_object_file_reader.rb:43:in `each'\n/src/app/models/logged_streaming_thread.rb:111:in `file_thread_body'\n/src/app/models/logged_streaming_thread.rb:49:in `thread_body'\n/src/app/models/streaming_thread.rb:47:in `block in start'"}

Additionally, the logs claim for each packet I am requesting: 
"severity":"ERROR","microservice_name":"CMD__TLM__API","container_name":"a02f5358118d","log":"Unknown packet <TARGET> <PACKET_NAME>

I was looking through the code the error is referencing. I have been trying to figure out why DECOM mode works and RAW causes this error. I believe it has something to do with the identify_and_defined_packet_data method.
The JSON packets don't use the identify_and_define_packet_data method. 
With the RAW mode packets, the packets are being read with "identify_and_define" = true. If you check buffered_packet_log_reader.rb line 41. The argument "identify_and_define" by default looks like it is true and does not look like any option to set it to false that I can tell. This causes the System class to be called to identify the packet.

### Multithreaded related issue?

I don't see any evidence that the System instance exists in the cmd_tlm_api container or process that is running the streaming_api.rb. I have been looking for System.instance() or System.setup_targets() to be called first (which establishes a System.instance() at the end of it) because without it, there is no system instance to check which telemetry definition is being checked. 

I think in this case it is ok to set the identify_and_define = false in the buffered_packet_log_reader.rb because the packet is built and expected to be sent out either way. This is what is happening in the DECOM case where it never appears to be identified since all values already exist. However, I am not aware of the entire impact of doing that, so some testing would need to be done. Any insight? Agree?

**Comment by jmthomas** [comment]
I was able to successfully extract RAW data using Data Extractor. Do you only see this using the APIs or can you reproduce in Data Extractor?
