### ISSUE TITLE
Bucket Explorer

### ISSUE THREAD

**Issue by ryanmelt** [OpenC3/cosmos#351]
Create a general purpose Bucket Explorer Tool that will work with any Bucket backend, and then remove Minio Console

**Comment by jmthomas** [comment]
Is this different from #144 Log Messages Tool?

**Comment by ryanmelt** [comment]
Yes - Log Messages Tool is a lightwight Kibana
This ticket is for a lightweight Minio Console (That works with every bucket backend)
