### ISSUE TITLE
@openc3/tool-common needs update

### ISSUE THREAD

**Issue by MTI-GMays** [OpenC3/cosmos#362]
Using custom tools in OpenC3 5.3.0 will result in continuous log out (401 issues). The tool would previously work in OpenC3 5.1.1. The npm/@openc3/tools-common is out of date. once the '\node_modules\@openc3\tool-common\src\services\openc3-api.js' is updated to the what 'cosmos-5.3.0\openc3-cosmos-init\plugins\packages\openc3-tool-common\src\services\openc3-api.js' has, the issue is resolved. Ticket #356 is having this issue. 

The latest npm/@openc3/tool-common is 5.0.6 while OpenC3 release 5.3.0 is on @openc3/tool-common 5.3.0.
https://socket.dev/npm/package/@openc3/tool-common

![Tools-common_issue](https://user-images.githubusercontent.com/119633180/211372466-1cad1cf8-c33a-4306-a4c6-dd2a877758ec.PNG)

**Comment by jmthomas** [comment]
Looks like we need to set the correct tag in NPM. Thanks @MTI-GMays!

**Comment by ryanmelt** [comment]
Fixed the tag on the 5.3.0 to latest. Also update the release process to tag correctly going forward.  
closed by #381

**Comment by MTI-GMays** [comment]
Thanks Ryan!
