### ISSUE TITLE
Telemetry Viewer can't run all ruby snippets

### ISSUE THREAD

**Issue by tsjordan-eng** [OpenC3/cosmos#363]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**
The telemetry viewer cannot run a ruby snippet that ran in COSMOS 4. It seems that the parser is broken. I think it has something to do with the `{` character.

**To Reproduce**

1. Create a telemetry screen that uses a more advance ruby construct like strings with `#{ expr }` or dictionaries `{"key" => "value"}` in the button action
3. click the button
4. When it doesn't work a little warning sign appears in the upper-left and clicking it reveals an incorrect syntax error

**Expected behavior**
I expect it to work as it does in COSMOS 4

**Screenshots**

Examples:

```
HORIZONTAL
BUTTON 'Set Boot Partition' 'api.cmd("EDU SET_LOAD_SWITCH with SWITCH_NUM IO32_DR_BOOT_DRIVE_USE_ALTERNATE, STATUS #{if api.get_named_widget("BOOT_PART").text == "A" then "0" else "1" end}")'
NAMED_WIDGET BOOT_PART COMBOBOX "A" "B"
VALUE XB1_MISRB_EDU POWER IO32_DR_BOOT_DRIVE_USE_ALTERNATE
END
```
`1673293822163: (error) SyntaxError: missing ) after argument list`

```
HORIZONTAL
NAMED_WIDGET BOOT_PART COMBOBOX "A" "B"
BUTTON 'Set Boot Partition' 'api.cmd("EDU", "SET_LOAD_SWITCH", {"SWITCH_NUM" => "IO32_DR_BOOT_DRIVE_USE_ALTERNATE", "STATUS"=> api.get_named_widget("BOOT_PART").text() == "A" ? 0 : 1})'
VALUE XB1_MISRB_EDU POWER IO32_DR_BOOT_DRIVE_USE_ALTERNATE
END
```
`1673293888076: (error) SyntaxError: Unexpected token '=>'`

**Environment (please complete the following information):**

- OS: RHEL 8
- OpenC3 COSMOS Version 5.2.0
- Browser
  -- [x] Edge
  -- [] Internet Explorer (IE)
  -- [] Google Chrome
  -- [] Chromium based browsers
  -- [] Mozilla Firefox
  -- [] Safari

**Comment by jmthomas** [comment]
Telemetry viewer widgets are now running Javascript not Ruby. We just created a ticket which allows for better multiline support so creating more complex logic is now much easier. Please see the Demo Inst [commanding](https://github.com/OpenC3/cosmos/blob/main/openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/screens/commanding.txt) screen for an example of what is possible. I'm sorry this isn't as well documented right now.
