### ISSUE TITLE
Migrate Script Doesn't Update Telemetry Screens

### ISSUE THREAD

**Issue by tsjordan-eng** [OpenC3/cosmos#364]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**
The migrate script brings over the old telemetry screen files, but doesn't update the syntax to use `api.cmd` and `api.get_named_widget`

**To Reproduce**

1. Migrate a target from COSMOS 4
2. Try to use a telemetry screen that utilizes `cmd` and/or `get_named_widget`

**Expected behavior**
The screens should be updated to the COSMOS 5 syntax

**Screenshots**
TLM file:
```
BUTTON 'Set Boot Partition' 'cmd("EDU SET_LOAD_SWITCH with SWITCH_NUM IO32_DR_BOOT_DRIVE_USE_ALTERNATE, STATUS  0")'
```
`1673294294679: (error) ReferenceError: cmd is not defined`

**Environment (please complete the following information):**

- OS: RHEL 8
- OpenC3 COSMOS Version 5.0.2
- Browser
  -- [x] Edge
  -- [] Internet Explorer (IE)
  -- [] Google Chrome
  -- [] Chromium based browsers
  -- [] Mozilla Firefox
  -- [] Safari

**Comment by jmthomas** [comment]
This is definitely an enhancement to the target / plugin migration script.
