### ISSUE TITLE
cli generator updates

### ISSUE THREAD

**Issue by ryanmelt** [OpenC3/cosmos#390]
1. Generated plugins should default to MIT license.  That will maximize utilization and not cause conflicts with Enterprise Edition.
2. Consider including generators for conversions, limits responses, widgets, microservices, and tools (perhaps just cloning an existing template repo?)
3. rake build VERSION=1.0.0 should not put timestamp in filename

**Comment by jmthomas** [comment]
The microservice template should utilize the @count and @state variables to provide status back to the CmdTlmServer
