### ISSUE TITLE
Script runner show environment variables

### ISSUE THREAD

**Issue by MTI-twalker** [OpenC3/cosmos#406]
I have found that to add an environment variable I need to use the bookmark button next to start and add them there.
However, SCRIPT->"Show environment" in the script runner does not include the environment variables located behind the bookmark button. Also, adding to the show environment also does not affect the environment.

I am not sure if these are linked or if I am using this wrong.

**Comment by jmthomas** [comment]
There is definitely a disconnect right now between the two. Thanks for the heads up.
