### ISSUE TITLE
Log to CmdTlmServer from microservice? 

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/cosmos#424]
Hello,

Is there a method to log messages into the CmdTlmServer from within a microservice? I have not found a way to do so.

My imports are:
```
require 'openc3/api/api'
require 'openc3/utilities/logger'
require 'openc3/microservices/microservice'

include OpenC3::Api
```

I have tried the following:
- module OpenC3 around file (does not work in a microservice)
- OpenC3::Logger.info(msg) 
- Logger.info(msg)

in the same microservice, the `crc = OpenC3::Crc32.new.calculate_crc32(packet)` line works, so I am referencing the class libraries correctly. Is there something I am missing? Essentially, I am attempting to debug a microservice without injecting telemetry into a "log" packet.

Thanks,

Dakota

**Comment by ryanmelt** [comment]
Logger is what does it.   You have to set the scope though, otherwise it goes into a "scopeless" log which isn't really shown anywhere... I need to think about that.   

```
      @logger = Logger.new
      @logger.scope = @scope
      @logger.microservice_name = @name
```

**Comment by GTI-Dakota** [comment]
Awesome, that worked! Thanks
