### ISSUE TITLE
Command Sequence tool for V5

### ISSUE THREAD

**Issue by MTI-twalker** [OpenC3/cosmos#425]
Are there any plans on porting the command sequence tool over to V5 from V4?

**Comment by jmthomas** [comment]
It never felt like Command Sequence was that well used. With the Calendar tool we have the ability to execute arbitrary scripts or send commands at future times. That was the original goal of Command Sender: to execute a block of commands with various delays to sort of simulate a time based command sequence. I think Calendar makes Command Sender OBE.

**Comment by MTI-twalker** [comment]
A team here uses the command sequence to for its export capabilities to generate ATS/RTS tables.

**Comment by ryanmelt** [comment]
We'll add this to our roadmap.  It is useful for building flight software command tables.   Will probably be several months though.

**Comment by jmthomas** [comment]
This could be a part of Table Manager if it understood the command definitions.
