### ISSUE TITLE
IGNORE_ITEM Has No Effect

### ISSUE THREAD

**Issue by schuuust** [OpenC3/cosmos#428]
**Describe the bug**
IGNORE_ITEM <item-name> does not have intended effect on telemetry. 

**To Reproduce**

1. Add `IGNORE_ITEM <item-name>` to `target.txt` (in target's directory)
2. Save and repackage gem
3. Reload the Gemfile in OpenC3
4. Open packet viewer or other tool
5. See the ignored item is present & updating in real time

Alternatively:
1. Confirm code ignoring certain items in default target INST in  openc3/openc3-init/plugins/packages/openc3-demo/targets/INST/target.txt
2. Check packet viewer and other tools to see ignored items present and updating

**Expected behavior**
Did not expect to see the ignored telemetry item or see it receiving updates

**Screenshots**
Contents of target.txt:
![image](https://user-images.githubusercontent.com/78887697/215896584-50b7f70d-58cf-481e-99dc-346017b4c80a.png)

Packet viewer showing items that should be ignored:
![image](https://user-images.githubusercontent.com/78887697/215898416-33ab5a86-e4ea-4aac-93e5-18bb40087354.png)

**Environment (please complete the following information):**

- OS: [e.g. Windows 10, Mac OS 10.13] Linux 20.04 & 22.04
- OpenC3 COSMOS Version [e.g. 5.0.6] OpenC3 COSMOS 5.0.4 & OpenC3 5.0.12
- Browser
  -- [] Internet Explorer (IE)
  -- [X] Google Chrome
  -- [] Chromium based browsers
  -- [X] Mozilla Firefox
  -- [] Safari

**Comment by ryanmelt** [comment]
dup of #368 
This will changed in our next release.
