### ISSUE TITLE
Command Only Target Breaks Microservice

### ISSUE THREAD

**Issue by MTI-twalker** [OpenC3/cosmos#449]
**Describe the bug**
A target with only command packets defined does not cause the plugin to crash but does cause the microservice operator to crash and the interface is never able to be built. It claims that " Telemetry target '<TARGET_NAME>' does not exist". Which, I guess it wouldnt?
FYI, Telemetry only targets do not break the microservice.

**To Reproduce**
1. openc3.sh cli generate plugin TEST
2. Delete tlm.txt file in the TEST/cmd_tlm folder
3. openc3.sh cli rake build VERSION=1.0.0
4. Upload plugin

The message log should provide a looping error of:
<html>
<body>

Unexpected process died... respawning! ruby interface_microservice.rb DEFAULT__INTERFACE__TEST_INT Stdout: {"time":1675451466815929900,"@timestamp":"2023-02-03T19:11:06.815+00:00","severity":"INFO","container_name":"eea904a757e5","log":"Microservice running from: ruby plugin_microservice.rb "} {"time":1675451466829905800,"@timestamp":"2023-02-03T19:11:06.829+00:00","severity":"INFO","microservice_name":"DEFAULT__INTERFACE__TEST_INT","container_name":"eea904a757e5","log":"Microservice initialized with config: {\"name\"=>\"DEFAULT__INTERFACE__TEST_INT\", \"folder_name\"=>nil, \"cmd\"=>[\"ruby\", \"interface_microservice.rb\", \"DEFAULT__INTERFACE__TEST_INT\"], \"work_dir\"=>\"/openc3/lib/openc3/microservices\", \"ports\"=>[], \"env\"=>{}, \"topics\"=>[], \"target_names\"=>[\"TEST\"], \"options\"=>[], \"parent\"=>nil, \"container\"=>nil, \"updated_at\"=>1675451420548484400, \"plugin\"=>\"openc3-cosmos-test-1.0.0.20230203191006.gem__20230203191020\", \"needs_dependencies\"=>false, \"secrets\"=>[]}"} {"time":1675451467700894900,"@timestamp":"2023-02-03T19:11:07.700+00:00","severity":"INFO","microservice_name":"DEFAULT__INTERFACE__TEST_INT","container_name":"eea904a757e5","log":"Ruby microservice DEFAULT__INTERFACE__TEST_INT file interface_microservice.rb passed syntax check "} {"time":1675451469035290800,"@timestamp":"2023-02-03T19:11:09.035+00:00","severity":"INFO","container_name":"eea904a757e5","log":"Microservice running from: ruby interface_microservice.rb DEFAULT__INTERFACE__TEST_INT"} {"time":1675451469055371000,"@timestamp":"2023-02-03T19:11:09.055+00:00","severity":"INFO","microservice_name":"DEFAULT__INTERFACE__TEST_INT","container_name":"eea904a757e5","log":"Microservice initialized with config: {\"name\"=>\"DEFAULT__INTERFACE__TEST_INT\", \"folder_name\"=>nil, \"cmd\"=>[\"ruby\", \"interface_microservice.rb\", \"DEFAULT__INTERFACE__TEST_INT\"], \"work_dir\"=>\"/openc3/lib/openc3/microservices\", \"ports\"=>[], \"env\"=>{}, \"topics\"=>[], \"target_names\"=>[\"TEST\"], \"options\"=>[], \"parent\"=>nil, \"container\"=>nil, \"updated_at\"=>1675451420548484400, \"plugin\"=>\"openc3-cosmos-test-1.0.0.20230203191006.gem__20230203191020\", \"needs_dependencies\"=>false, \"secrets\"=>[]}"} {"time":1675451470484051300,"@timestamp":"2023-02-03T19:11:10.484+00:00","severity":"INFO","microservice_name":"DEFAULT__INTERFACE__TEST_INT","container_name":"eea904a757e5","log":"Retrieving DEFAULT/target_archives/TEST/TEST_current.zip from targets bucket"} {"time":1675451470634616500,"@timestamp":"2023-02-03T19:11:10.634+00:00","severity":"INFO","microservice_name":"DEFAULT__INTERFACE__TEST_INT","container_name":"eea904a757e5","log":"Processing target definition in file '/tmp/d20230203-74-b4ew1m/targets/TEST/target.txt'"} {"time":1675451470677751900,"@timestamp":"2023-02-03T19:11:10.677+00:00","severity":"INFO","microservice_name":"DEFAULT__INTERFACE__TEST_INT","container_name":"eea904a757e5","log":"TEST_INT: shutdown requested"} {"time":1675451470678550600,"@timestamp":"2023-02-03T19:11:10.678+00:00","severity":"INFO","microservice_name":"DEFAULT__INTERFACE__TEST_INT","container_name":"eea904a757e5","log":"TEST_INT: stop requested"}  Stderr: interface_microservice.rb:612:in `block in stop': undefined method `stop' for nil:NilClass (NoMethodError)          @handler_thread.stop                        ^^^^^ 	from interface_microservice.rb:608:in `synchronize' 	from interface_microservice.rb:608:in `stop' 	from interface_microservice.rb:626:in `shutdown' 	from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.3.0/lib/openc3/microservices/microservice.rb:127:in `block in initialize' 

interface_microservice.rb:330:in `packets': Telemetry target 'TEST' does not exist (RuntimeError) 	from <----Here is your error.

interface_microservice.rb:330:in `block in initialize' 	from interface_microservice.rb:327:in `each' 	from interface_microservice.rb:327:in `initialize' 	from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.3.0/lib/openc3/microservices/microservice.rb:51:in `new' 	from /usr/lib/ruby/gems/3.1.0/gems/openc3-5.3.0/lib/openc3/microservices/microservice.rb:51:in `run' 	from interface_microservice.rb:636:in `<main>'
--

</body>
</html>

**Environment (please complete the following information):**

Windows 10
- OpenC3 COSMOS Version V5.3.0
- Browser
  -- [] Internet Explorer (IE)
  -- [X] Google Chrome
  -- [] Chromium based browsers
  -- [] Mozilla Firefox
  -- [] Safari

**Comment by ryanmelt** [comment]
Confirmed.  Will fix in 5.4.2
