### ISSUE TITLE
Override Flag on Cleanup

### ISSUE THREAD

**Issue by jeffstjean** [OpenC3/cosmos#451]
Can the cleanup command in the openc3.sh/bat scripts accept a flag that will automatically accept the prompt? This would allow automated tooling to still be able to run these commands.

A simple change (for the bash script) would maybe look like this:
```
cleanup )
  if [ "$1" == "force" ]
    docker-compose -f compose.yaml down -t 30 -v
  else
    echo "Are you sure? Cleanup removes ALL docker volumes and all COSMOS data! (1-Yes / 2-No)"
    select yn in "Yes" "No"; do
      case $yn in
        Yes ) docker-compose -f compose.yaml down -t 30 -v; break;;
        No ) exit;;
      esac
    done
  fi
  ;;
```

and could be executed with `./openc3.sh cleanup force

**Comment by ryanmelt** [comment]
I like this.  5.4.2 is probably coming soon and will try to get it in.
