### ISSUE TITLE
Bucket Explorer upload

### ISSUE THREAD

**Issue by jmthomas** [OpenC3/cosmos#452]
Bucket Explorer should support upload at which point we can deprecate minio console

**Comment by jeffstjean** [comment]
Can I ask that the bucket explorer list all folder in minio and not just config, logs, and tools?

**Comment by ryanmelt** [comment]
Those are the three different buckets.  After you click on one you should be able to see all the folders.

**Comment by MTI-twalker** [comment]
I have created certain tools that utilize their own buckets as to not interact with any other directories that may have certain  processes interacting with them.

**Comment by ryanmelt** [comment]
Opened a ticket to support additional buckets: https://github.com/OpenC3/cosmos/issues/454
