### ISSUE TITLE
Custom Widget Javascript imports cause error.

### ISSUE THREAD

**Issue by CharlotteMorrison** [OpenC3/cosmos#458]
When developing custom widgets if I add in a javascript import (including the OpencC3API, or just a JS file) OpenC3 screens no longer recognize the widget.  If I comment out the import statements, the widget can be found by the screens and there is no error.

Error Message: 1675560878209: (error) Error: Unknown widget: RegisterWidget

I installed the newest relase of OpenC3 and I am having the same issue.  I had a collegue test it on their system as well and he is experiencing the same issue.   It fails with the addition import statements, even if there are no calls to the file.

Sample import statements-

`import { OpenC3Api } from '@openc3/tool-common/src/services/openc3-api'`
`import { customJavacript } from './scripts/customJsFile.js`

Current system:

- OS: Windows 11
- OpenC3 COSMOS Version 5.4.2, 5.3.0
- Browser: Google Chrome

**Comment by ryanmelt** [comment]
Did you try starting from our new widget template project?
https://github.com/OpenC3/openc3-widget-template

**Comment by CharlotteMorrison** [comment]
Thank you for the quick response- I am able to build the widgets properly with the .js imports using the the openc3-widget-template.   It didn't work using the instructions in the documentation unless I removed all the .js import statements/code.
