### ISSUE TITLE
Upload file functionality

### ISSUE THREAD

**Issue by wiatrp** [OpenC3/cosmos#477]
In this PR (https://github.com/OpenC3/cosmos/pull/466) the ability to upload to a bucket was added and I'm wondering what the reasoning was behind this strategy instead of using a standard `put_object` call? We implemented our own API call a while back and borrowed from how `gem_model.rb` works which I thought worked well. 

A couple drawbacks I see from the new implementation I see are:
1. Requires two calls from the front end instead of just one. With a typical `put_object` implementation we can just let the back end handle everything  in one call.
2. Requires a little more set up work on the front end since there are two separate calls. If I want to replicate this anywhere else (uploading files) it's more code up front. I think these could be combined into one function that exported from the tool-base JS library.

Overall, it seems like it would be simpler to just let the back end handle everything with a `put_object` call.

**Comment by ryanmelt** [comment]
We're using presigned requests which provide several benefits:

1. We don't have to expose the buckets to the internet
2. The client takes on the burden of uploading files to the bucket without going through our web server as a proxy (it just goes through our load balancer).  This is really beneficial for large files.

gems are saved to either a docker volume (or an NFS mount in Kubernetes), which has to go through our server.
