### ISSUE TITLE
How to Render in Multiple Locals Variables from Plugin.txt

### ISSUE THREAD

**Issue by dlackner** [OpenC3/cosmos#481]
I am trying to render in some locals variables from my plugin.txt file into a shared cmd definition file in the lib folder. 

├targets
├── lib
├────_shared_cmd.txt
├── Flight_Computer_Target
├──── cmd.txt
├plugin.txt

In my plugin.txt file I have the following:
VARIABLE min_uint_8 -255
VARIABLE max_uint_8 255
VARIABLE min_uint_16 -65535
VARIABLE max_uint_16 65535
VARIABLE min_uint_32 -4294967295
VARIABLE max_uint_32 4294967295

In my cmd.txt file I have the following: 
<%= render  "../../../lib/_shared_cmd.txt", locals: { max_uint_16:max_uint_16, min_uint_32:min_uint_32, max_uint_32:max_uint_32  } %>

Is there a better way to render in all the local variables from my plugin.txt file into _shared_cmd.txt?

Something like:
<%= render  "../../../lib/_shared_cmd.txt", locals: { locals.plugin.txt } %>

Thanks for the help!

**Comment by jmthomas** [comment]
If you're rendering a template the only way to pass variable is using the locals syntax like you're doing. I'd argue min_uint_8 is more of a constant than a variable though.
