### ISSUE TITLE
Docker is dropping support for "docker-compose" (v1).  Need to switch to "docker compose" (v2)

### ISSUE THREAD

**Issue by ryanmelt** [OpenC3/cosmos#491]
In June docker is removing docker-compose. (v1)  Need to update to "docker compose". (v2)

**Comment by ryanmelt** [comment]
https://docs.docker.com/compose/compose-v2/

**Comment by finchlt** [comment]
If it helps, we have been using docker compose v2 with COSMOS for a while now. I have a compatibility script installed at `/usr/local/sbin` with the only line being `docker compose $@`. This just wraps all `docker-compose` calls to `docker compose`
