### ISSUE TITLE
Return metadata from bucket objects

### ISSUE THREAD

**Issue by wiatrp** [OpenC3/cosmos#496]
**Is your feature request related to a problem? Please describe.**
We upload objects with metadata and need a way to get the metadata back when listing all the objects. It seems like the `list_objects_v2` endpoint doesn't return object metadata with it and AWS make it a little difficult to get metadata from all objects.

**Describe the solution you'd like**
It would be nice to be able to return metadata with the same endpoint as getting all files (`/storage/files/:bucket/(*path)`). To get metadata you can use the [head_object](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#head_object-instance_method) call and return it with the object. 

[Here](https://gist.github.com/mihaiserban/1f35d488405812f2bbd4b16e38e4afb5) is an example of a gist that I think could work. The user can supply a parameter if they want to call to also include metadata. To do this you have to list the objects, then iterate through each object to head it, and then you can add the metadata to the payload that's returned to the user.

**Comment by jmthomas** [comment]
closed by #505
