### ISSUE TITLE
Add multiple select to script combo_box

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/cosmos#506]
Hello,

I didn't see any documentation regarding a combo/checkbox in the script runner that returns a list of items, instead of only one. Is there something like this implemented but not documented?

ex:
T===============T
| Please choose options  |
|_________________________ |
|    [  ] 1                            |
|    [  ] 2                            |
|    [x] 6                            |
|    [x] 7                            |
|    [  ] 10                          |
L===============J

returns [6, 7]

Thanks,

Dakota

**Comment by jmthomas** [comment]
I'm afraid not. We have a combo_box but it doesn't support multiple select.
