### ISSUE TITLE
TLM Viewer Performance Issue with out of order Log

### ISSUE THREAD

**Issue by pankakes14** [OpenC3/cosmos#525]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**
I'm seeing performance of the telemetry viewer and packet viewer grind to a halt very shortly after connecting to a target that is streaming a fairly large amount of telemetry. The packet rate is approximately 300 packets per second and when initially connecting it seems like it can keep up, but after about 15 seconds, it starts to lag behind and starts displaying packets that are from several seconds in the past. If I wait for a little while longer all of the packets go stale and update about once every 10 seconds (if at all).

Interestingly, I'm also seeing this log message which leads me to believe the tlm packet buffer is too small:
```
Log writer out of order time detected (increase buffer depth?): 2023-03-02 16:35:35 +0000 2023-03-02 16:34:15 +0000
```

I tried increasing the buffer depth to 150 `TLM_BUFFER_DEPTH` and still saw the issue, then increased it to 1000 at which point the telemetry viewer almost stopped working completely (immediately showed stale telemetry and barely updated at all).

I'm running on a new M1 mac and it's not consuming all of the CPU, however, I will say the `operator` image is using slightly over 100% CPU. Maybe that's the bottleneck.

Let me know if I can collect any more information or try anything! Thanks.

**To Reproduce**

1. Create a target/test that sends a fairly large amount of telemetry 
2. Create telemetry page in tlm viewer to display a page updated every 1 second. 
3. After some time, will see packets go stale and display not updating

**Expected behavior**
Expected that telemetry viewer displays the latest packets received and is able to keep up with incoming telemetry stream. 

**Screenshots**

**Environment (please complete the following information):**

- OS: Mac OS 13.01
- OpenC3 COSMOS Version v5.5.1
- Browser
  -- [] Internet Explorer (IE)
  -- [x] Google Chrome
  -- [] Chromium based browsers
  -- [] Mozilla Firefox
  -- [] Safari

**Comment by jmthomas** [comment]
How much RAM do you have and how much do you have allocated to Docker? I have 5 CPUs and 10GB allocated on my Macbook Air. Also do a `docker stats` and let us know what you see. Note the TLM_BUFFER_DEPTH should be enough to consume all the packets for your target. Try setting it to 300 and dialing up from there.

**Comment by pankakes14** [comment]
I previously had 8GB allocated, but just bumped it to 10GB just to be consistent. I also have 5 CPUs allocated as well. Here's the usage while streaming packets.
```
CONTAINER ID   NAME                                       CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
0cb2b7176fc4   cosmos-openc3-cosmos-cmd-tlm-api-1         0.53%     278.3MiB / 9.718GiB   2.80%     28.9MB / 23MB     3.88MB / 43.9MB   74
cd4db9e0e2ab   cosmos-openc3-operator-1                   110.01%   360.8MiB / 9.718GiB   3.63%     266MB / 3.25GB    8.19kB / 97.4MB   45
4d2baafe9432   cosmos-openc3-cosmos-script-runner-api-1   0.02%     110MiB / 9.718GiB     1.11%     1.7kB / 0B        5.71MB / 12.5MB   27
e69819039974   cosmos-openc3-traefik-1                    0.17%     30.01MiB / 9.718GiB   0.30%     5.23MB / 5.34MB   2.27MB / 0B       11
6b694234ba5f   cosmos-openc3-redis-1                      4.48%     17.78MiB / 9.718GiB   0.18%     191MB / 47.8MB    0B / 9.54MB       5
5177a7f8d4b8   cosmos-openc3-redis-ephemeral-1            30.34%    190.4MiB / 9.718GiB   1.91%     3.08GB / 235MB    0B / 0B           5
0e89fff344ad   cosmos-openc3-minio-1                      0.03%     137MiB / 9.718GiB     1.38%     65.9MB / 6.38MB   13.7MB / 70.6MB   12
```

I also bumped the TLM_BUFFER_DEPTH up to 500 and curiously I still see the out of order messages. I'll continue to bump this up and see whether I can get the messages to go away, but wondering if it's just unable to keep up for some reason. It might be worth noting that when I increase the tlm buffer the tlm vewier seems to be blocked even more, and packets update even less frequently than when it's at a lower value.

**Comment by ryanmelt** [comment]
You might be overwhelming the decom process.   How many different packets make up your 300Hz rate?  If it is more than one, we can break up the processing to improve performance.   Handling a very fast single packet is also possible, but I don't have the hooks built-in yet to support that.

**Comment by pankakes14** [comment]
Oh yeah all 300 are pretty much unique packets. There's ~450 telemetry packet definitions in the database and of those, about 300 are being sent every second. The target has a lot of applications that send several pages each of unique telemetry once per second. They're spread out over that second (not all 300 at once) but still a pretty large number.

**Comment by ryanmelt** [comment]
Great.  You can try this breaking up the decom in your plugin.txt then using this:
https://openc3.com/docs/v5/plugins#target_microservice

Will look like:
TARGET ...
  TARGET_MICROSERVICE DECOM
    PACKET packet_name1
    PACKET packet_name2
    ...

If you list half your packets that will run two seperate decom microservices, each handling half the packets.   You can repeat TARGET_MICROSERVICE DECOM again to get a third process, etc.   Each process will be able to use up to an entire CPU core.

**Comment by pankakes14** [comment]
Ah that did it, thank you so much! That makes a huge difference.
