### ISSUE TITLE
How is data stored once processed

### ISSUE THREAD

**Issue by RossWilliamson** [OpenC3/cosmos#528]
I'm having difficulty in understanding how telemetry is stored once it is sent to openC3.  Is the raw data also output to a file or is the telemetry processed and put into a database.  For example if for some reason openC3 crashes do you still have access to historical data either through the UI or at least via the dumped telemetry files.  If it is dumped telemetry files is there a way to reload them back into openC3 for playback or viewing?

**Comment by jmthomas** [comment]
Data is processed and pushed into Redis streams. Microservices pull the raw data off into log files which are written to bucket storage (Minio). Other microservices decommutate (turn into engineering values) the data and write it to bucket storage. Further microservices reduce the data to min, hour, day aggregations for ease of use over long time periods. So the data is all stored and available to tools as well as the streaming api.
