### ISSUE TITLE
Using S3 buckets instead of MinIO

### ISSUE THREAD

**Issue by wiatrp** [OpenC3/cosmos#529]
I'm having some trouble figuring out how to use AWS buckets over minio. I was able to set my credentials and during the build process every built just fine to AWS S3 buckets I've created. However, when I try to access COSMOS (localhost:2900) I get an access denied error. I made sure to make the tools bucket public with the same bucket policy from your AWS code.

![image](https://user-images.githubusercontent.com/7209185/222872484-c038627a-f599-4542-ae5a-e3c1f3de6f54.png)

To me, it looks like COSMOS is still trying to route to minio from traefik and isn't able to access the tools index bucket because it doesn't exist. 

I was also wondering if it's required to have the tools bucket set to public, or if there is a way you are doing it on enterprise without the bucket needing to be public? If the tools bucket must be public then S3 isn't really useable. Unless you didn't intend the tools bucket to be used with S3.

**Comment by jmthomas** [comment]
COSMOS Enterprise is required to use S3 buckets or GCP Cloud Storage. Please reach out to support@openc3.com to get started with Enterprise.
