### ISSUE TITLE
Cable Streaming Capability

### ISSUE THREAD

**Issue by bradenvirdellgenevatech** [OpenC3/cosmos#531]
Hello,

It has come to my attention that one of my previously working custom widgets is no longer working. From my digging it seems like the cable subscription capability has been updated. I have tried a few different things, specifically updating the subscription key a few different ways based on what I am seeing in the Graph.vue file. None of these have succeeded so far I was wondering if you could take a look at what I currently have to see if there are any issues? 

Originally I was subscribed to an entire packet with the following:
![image](https://user-images.githubusercontent.com/111302076/223177952-0feedc99-907d-425f-826c-3f1d6d362ea7.png)
And the subscription perform looks like this:
![image](https://user-images.githubusercontent.com/111302076/223178114-8f5e445e-da08-4b4a-9938-3c5b9b0ab317.png)

My updated subscription key looks like this, in this one I am trying to just subscribe to a single tlm:
![image](https://user-images.githubusercontent.com/111302076/223178305-5e8c8d07-6c93-44d1-aa0a-bcae258e6f03.png)
And the subscription perform looks like this:
![image](https://user-images.githubusercontent.com/111302076/223178749-47c794eb-3e51-44d0-80c8-c56032435f03.png)

Any help would be greatly appreciated. Thank you.

**Comment by jmthomas** [comment]
The `subscriptionKey` function at the bottom of Graph.vue shows the details of the key:
```
    subscriptionKey: function (item) {
      let key = `${item.reduced}__TLM__${item.targetName}__${item.packetName}__${item.itemName}__${item.valueType}`
      if (
        item.reduced === 'REDUCED_MINUTE' ||
        item.reduced === 'REDUCED_HOUR' ||
        item.reduced === 'REDUCED_DAY'
      ) {
        key += `__${item.reducedType}`
      }
      return key
    },
```
Note it's being called using map which maps each item in `this.items` to `item` in the function. Your code appears to use `this.parameters` every time which is probably the issue. The overall structure of the key looks correct.

I'm not sure what you're trying to accomplish but note that all the Graph widgets (https://openc3.com/docs/v5/telemetry-screens#linegraph) now support a HISTORY setting which displays graph history.

**Comment by bradenvirdellgenevatech** [comment]
Currently I am just trying to stream a string TLM to a widget and when the TLM updates it the widget will update along with it, while holding pervious data to be viewed. 
The parameters are simply the Target, packet, item. I will try and add in the extra bits you have and see if that works. I will post again successful or not.

**Comment by bradenvirdellgenevatech** [comment]
I am now able to get the wanted TLM to the widget, thank you for the pointers.
