### ISSUE TITLE
New Suite template missing super()

### ISSUE THREAD

**Issue by MTI-twalker** [OpenC3/cosmos#533]
The current suite template needs a super on its initialize because it ends up causing weird errors that are a bit hard to track to super(). 

![image](https://user-images.githubusercontent.com/101339004/223462147-501a35c5-9f48-4dec-9afe-53bf8515ecfc.png)

**Comment by jmthomas** [comment]
We eliminated the need for super in #399. Is there something specific you're running into?

**Comment by MTI-twalker** [comment]
I was still using 5.3.0 in the case of testing our script. Verified no error on template with 5.5.1. Thank you!
