### ISSUE TITLE
Add Crc8

### ISSUE THREAD

**Issue by tj-scherer** [OpenC3/cosmos#558]
I think this is pretty self-explanatory, it would be great to have the ability to perform a CRC-8 calculation, same as the 16, 32, and 64 defined in openc3/utilities/crc.rb.

**Comment by ryanmelt** [comment]
We can add this, but just note that any 8-bit checksum is going to have very high false positives (1/256 chance).

**Comment by tj-scherer** [comment]
Thank you for the quick response and the information. I am creating a protocol for RMAP (remote memory access protocol), which includes CRC-8 as part of the standard. It will be very helpful to be able to use the built-in resources. Thank you!
