### ISSUE TITLE
Is there a way for a protocol to derive if it is READ, WRITE, or both?

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/cosmos#564]
Hello,

after reviewing [this protocol file](https://github.com/OpenC3/cosmos/blob/main/openc3/lib/openc3/interfaces/protocols/protocol.rb), I don't see how a protocol can understand if it has read_allowed and write_allowed, like an interface does. Is there a sneaky clever way to do this where the protocol can derive this, independent of using a get_interface call and parsing that? For now, I have read/write args in my constructor to do this, but I don't feel its as clean and it adds 2 extra args
![image](https://user-images.githubusercontent.com/111302074/228283494-997c0fa3-6d13-47db-a263-80d8d07b5ad4.png)

Thanks,

Dakota

**Comment by ryanmelt** [comment]
Protocols have access to their associated interface.
```
@interface.read_allowed?
@interface.write_allowed?
```

**Comment by GTI-Dakota** [comment]
Oh, good to know. Thanks!

**Comment by GTI-Dakota** [comment]
This didn't work in the initialize() protocol function, unfortunately. 

the code:
![image](https://user-images.githubusercontent.com/111302074/228290179-34494101-ef5a-49d4-a9bc-e442e243d293.png)


The error when loading the gem
> _protocol.rb:53:in `initialize': undefined method `write_allowed?' for nil:NilClass (NoMethodError)

**Comment by GTI-Dakota** [comment]
It works in the connect_reset, so I have reason to believe we are able to reference @interface if the protocol has been intialized.

**Comment by ryanmelt** [comment]
Not going to work in initialize.  Should work everywhere else.
