### ISSUE TITLE
Is there a way to create a "Bidirectional" interface that has an endpoint for write, and a different endpoint for read?

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/cosmos#565]
Hello,

At the moment my architecture is as follows:

**INTERFACE_1** connect to a server (192.168.10.78) on port 9998 for **writing data**
**INTERFACE_2** connect to a server (192.168.10.78) on port 9999 for **reading data**
**ROUTER_1** opens up port 9996 on the COSMOS Side so my app can send data through **INTERFACE_1**
**ROUTER_1** opens up port 9997 on the COSMOS Side so my app can receive data through **INTERFACE_2**

Is there an intelligent way to somehow tie my uplink and downlink to a single COSMOS port? such as ONLY 9996 so my app on my computer only needs to set up a single TCP Server for read/write? This may be an elementary question, but I figured I'd ask.

Thanks,

Dakota

**Comment by ryanmelt** [comment]
Are these different targets?  If not, you can configure our TCP/IP interfaces with different read and write ports.
