### ISSUE TITLE
Is there a way to create a "run-only" user for scripts?

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/cosmos#578]
Hello,

Apologies if this has already been addressed. Is there a user permission I can set in keycloak that only allows a user to run scripts (not save/overwrite) and nothing else? We have some locked down scripts and do not wish test engineers to accidentally save over them when running them for validation tests.

Thank you,

Dakota

**Comment by jmthomas** [comment]
Created issue in enterprise
