### ISSUE TITLE
Derived type in commands

### ISSUE THREAD

**Issue by timothyscherer** [OpenC3/cosmos#579]
The description for [parameters](https://openc3.com/docs/v5/command#parameter) includes the option to define derived types. I attempted to do so, following the described format and a few others, but none seemed to work. Is this an error in the documentation, or am I just doing something wrong?

My end goal was to implement some variable length fields by allowing the user to specify values in the DERIVED fields, then add those bytes in a protocol's read_data(), but that also probably isn't the greatest solution, since it seems most interfaces don't send_raw(), and instead send_packet().

**Comment by ryanmelt** [comment]
I haven't seen anyone do this, and I'm not actually sure what happens when you try to write a DERIVED item.   I don't think that is supported, but will look into it.
