### ISSUE TITLE
Monospace font where appropriate

### ISSUE THREAD

**Issue by tsjordan-eng** [OpenC3/cosmos#583]
The GUI might look better and be more functional with monospace font in select places

* Plugin.txt editor (I didn't realize it was editable until recently. Maybe use the script-runner editor here?)
* Plugin output
* Command sender History at the bottom
* Log messages, especially stderr and stdout where lines need to match up.
* generally anywhere there is code or config or stdout

@jmthomas, we spoke about this

**Comment by ryanmelt** [comment]
@jmthomas Already did this in several places.  See https://github.com/OpenC3/cosmos/pull/574

**Comment by jmthomas** [comment]
See #569 where we'll implement plugin.txt logic to force a selection as well as add the ACE editor.

However, there are a number of other places where I agree we should use monospace fonts. All the Admin tabs where we view configuration as well as the Redis tab.
