### ISSUE TITLE
Is there a way to downgrade/silence the DEFAULT_CLEANUP microservice's severity?

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/cosmos#584]
Hello,

When my server is idle, I see log message like this pretty continuously (due to our logging policy)

> Time                                   | Severity                 | Source                                                       | Message
> 2023-04-05 09:54:14.966   | INFO                      | DEFAULT__CLEANUP__MY_TARGET           | Deleted 2 MY_TARGET log files

Is there any way to silence this or downgrade the severity to "DEBUG"?

Thanks,

Dakota

**Comment by ryanmelt** [comment]
I agree we should reduce this log level to debug.
