### ISSUE TITLE
How to enable/disable data retention during runtime

### ISSUE THREAD

**Issue by twfth9** [OpenC3/cosmos#598]
We have a SCPI device that we are constantly polling data from but there are times when we don't wish to retain the telemetry data we receive, such as when an input signal is disconnected and we're reading useless data. At a high data rate this wasted data can add up quickly, and we would like a way to control when this data is worth logging or could be discarded.

Is there a way to dynamically toggle logged data retention for a target, akin to modifying the `LOG_RETAIN_TIME` or `DONT_LOG` status during runtime? Better yet, is it possible to alter retention of individual telemetry packets?

**Comment by jmthomas** [comment]
The COSMOS philosophy is to log everything that's attached. I would recommend `disconnect_interface(name)` and then `connect_interface(name, *params)` when you're ready to log again.
