### ISSUE TITLE
General flow from Router -> Interface -> Hardware 

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/cosmos#609]
I was taking a look at your flowgraphs here: https://openc3.com/docs/v5/protocols and they are very helpful. 

After reading through your github code, as I understand it, if I have the following architecture: 

Client <-> Router <-> Interface <-> Hardware

When the router is reading/writing, it is not being passed data correctly, but rather through a Topic, which would mean that the data is passed to Redis in between the router and interface.

So in my head, the flow is:

Client <----TCP---> Router <----Redis Topic---> Redis <----Redis Topic---> Interface <----TCP---> Hardware

Is this correct?

Thanks,

Dakota

**Comment by GTI-Dakota** [comment]
Updated to include Redis in flow

**Comment by ryanmelt** [comment]
That is correct.

**Comment by GTI-Dakota** [comment]
Thanks!

**Comment by GTI-Dakota** [comment]
> it is not being passed data correctly

I just realized that the "correctly" is supposed to say "directly". Totally changes the meaning of my sentence. My apologies
