### ISSUE TITLE
multi-line definition with string interpolation for local_screen

### ISSUE THREAD

**Issue by MTI-twalker** [OpenC3/cosmos#627]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**
The string interpolation requires the use of double-quote. In the example single quote is used and works as expected.

Introducing string interpolation and multi-line causes some instrumented code to inject itself into the string causing a bad screen definition. The \ at the end of each line worked for most lines until #{} was used.

In an attempt to find a work around, the only solution I could come up with was using \n and not using multi-line formatting. Example:
definition = "SCREEN AUTO AUTO 1.0 \n VERTICALBOX 'Test Screen' \n LABELVALUE #{target} #{packet} #{item} \n  END"
local_screen("TEST", definition)

**To Reproduce**
Create a local screen definition with string interpolation and multi-line formatting
```
target = "INST"
packet = "HEALTH_STATUS"
item = "TEMP1"
definition = "
  SCREEN AUTO AUTO 1.0 
    VERTICALBOX 'Test Screen' 
    LABELVALUE #{target} #{packet} #{item} 
  END"
local_screen("TEST", definition)
```
Then select the edit button to show the screen definition. You should see instrumented code injected. This causes issues if you try to add more than 1 value to the screen.

**Expected behavior**
The definition's string should be the only injected string into the screens definition.

**Environment (please complete the following information):**

- OS: Windows 10
- OpenC3 COSMOS Version 5.6.0
- Browser
  -- [] Internet Explorer (IE)
  -- [x] Google Chrome
  -- [] Chromium based browsers
  -- [] Mozilla Firefox
  -- [] Safari

**Comment by ryanmelt** [comment]
I'll see what we can do with instrumentation.  Another syntax that I expect will work is:
```
d = ""
d << "SCREEN AUTO AUTO 1.0\n"
d << "  VERTICALBOX 'Test Screen'\n"
...
```
