### ISSUE TITLE
Screen ERB error should be warning instead of crash

### ISSUE THREAD

**Issue by MTI-twalker** [OpenC3/cosmos#660]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Is your feature request related to a problem? Please describe.**
When uploading a gem, if there is an ERB error when processing the screens then it crashes the gem and fails the entire upload. Since screens are configurable after the fact and are not depended on by other processes, these should be warnings instead of complete fails. In the past, a pending ticket on a screen has caused the gem to be unusable so the "in-progress" screen had to be deleted in order to continue testing other stuff. 

**Describe the solution you'd like**
When ERB errors occur on screens, allow the gem to complete its upload but with warnings that the screens errored.

**Comment by jmthomas** [comment]
I think this is reasonable. However the ERB is only run during the installation so you may end up with a pretty hard to modify screen.
