### ISSUE TITLE
Add new API to build and return command binary

### ISSUE THREAD

**Issue by ryanmelt** [OpenC3/cosmos#663]
This will be the easiest way for external tools to build binary commands.

**Comment by jmthomas** [comment]
How will this be different from what [`get_command`](https://openc3.com/docs/v5/scripting#get_command-since-500) and [`get_cmd_buffer`](https://openc3.com/docs/v5/scripting#get_cmd_buffer) return?

**Comment by ryanmelt** [comment]
This will build the command binary without actually sending the command
