### ISSUE TITLE
Raw Telemetry view in CmdTlmServer is centered, but maybe shouldn't be?

### ISSUE THREAD

**Issue by scandey** [OpenC3/cosmos#664]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**

Raw Telemetry Packet view stays centered on the screen regardless of size of incoming packet, causing the buttons (like the pause button) to move around on the screen. If I am skimming through many sized packets looking for a specific one (for instance, a wrapped packet raw view that might include one specific packet I want), I have to hunt for the pause button when the window re-centers on the screen. 

**To Reproduce**

Open raw viewer on any packet whose length changes.

**Expected behavior**

While this kind of "modal"(?) window makes sense, I would like the top of the window to stay consistently placed on the screen so I can quickly access the pause button. 

**Screenshots**

<img width="1352" alt="image" src="https://github.com/OpenC3/cosmos/assets/1695225/fbb0b3f8-a3de-4c9c-95bf-ed33fe9c72f4">

<img width="1352" alt="image" src="https://github.com/OpenC3/cosmos/assets/1695225/7500c44d-c196-41ec-ac56-fc59374b4b1c">

**Environment (please complete the following information):**

- OS: Mac OS 13.3.1
- OpenC3 COSMOS Version 5.6.1
- Browser
  -- [] Internet Explorer (IE)
  -- [] Google Chrome
  -- [] Chromium based browsers
  -- [] Mozilla Firefox
  -- [x] Safari

**Comment by jmthomas** [comment]
Thanks this is definitely an annoying usability issue.
