### ISSUE TITLE
Is there a way to generate a TLM Definition given a hash?

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/cosmos#665]
Hello,

I have a JSON string retrieved from hardware that I convert to a hash. Is there an easy way to "create" a TLM def if I save off that string/hash? Or is this something that I will just need to write a quick script for? Additionally, it looks like TLM defs do not natively support boolean types. Am I correct?

Thanks,

Dakota

**Comment by jmthomas** [comment]
I think you'll have to create a script if you want to automate generating a telemetry definition.

We basically support Boolean types by providing states such as:

```
    APPEND_ITEM BOOL 8 UINT "Boolean"
      STATE FALSE 0
      STATE TRUE 1
```

**Comment by GTI-Dakota** [comment]
Sounds good. Thanks for the info!
