### ISSUE TITLE
Help using the bucket_load lib

### ISSUE THREAD

**Issue by bradenvirdellgenevatech** [OpenC3/cosmos#692]
Hello,

I am currently testing out the 5.8.1 updates, specifically the bucket load capability.
I am having some trouble making it work. Attached are the error I am getting, my microservice, the file i'm trying to call, the plugin, and the file structure I have.

Any help would be appreciated.
Thanks,
![error](https://github.com/OpenC3/cosmos/assets/111302076/d2bdff14-4922-4a73-b7d7-ddc6b430a764)
![file struct](https://github.com/OpenC3/cosmos/assets/111302076/96780132-6b94-43a7-a2b5-3e938f164d78)
![ms](https://github.com/OpenC3/cosmos/assets/111302076/236fd582-a375-46ab-849b-700d7eb15c54)
![procedures_fiel](https://github.com/OpenC3/cosmos/assets/111302076/bd51ba3f-b2fe-4ade-b080-09f9052819c4)
![the plugin](https://github.com/OpenC3/cosmos/assets/111302076/fe15ab4e-c9ec-4ba1-83e2-a98008d46638)

Braden V.

**Comment by ryanmelt** [comment]
This is currently failing because it doesn't know the scope.
I'll make that autodetect the scope better for the next release.  Until then:

Add:
$openc3_scope = 'DEFAULT'

before:
require '5_8_1_UPDATE/procedures/lib_test.rb'

**Comment by ryanmelt** [comment]
Or even better:

$openc3_scope = ENV['OPENC3_SCOPE']

**Comment by bradenvirdellgenevatech** [comment]
Easy fix on my side, thank you for the help
