### ISSUE TITLE
Installing gems that need extra Libs to complete

### ISSUE THREAD

**Issue by bradenvirdellgenevatech** [OpenC3/cosmos#703]
Hello,

I have been using the openc3s ability to install 3rd party ruby gems through the .gemspec file. I am have good success with most of the gem except for "rmagick". From what I gather I am missing the lib "imagemagick" and "imagemagick-dev". What would be the best way to get these libs into the proper container (I assume it is the operator).
![image](https://github.com/OpenC3/cosmos/assets/111302076/a516fe58-7f04-45b2-9e7f-9e097caff1eb)

**Comment by jmthomas** [comment]
It's been a while since I've played with rmagick but it's a pain in the butt due to all the dependencies. I think you'll have to build your own custom operator container and add the required packages.

**Comment by bradenvirdellgenevatech** [comment]
That's what I have been attempting, I will keep trying a few things.

**Comment by jmthomas** [comment]
Here's a thread where someone got v6 to work: https://github.com/rmagick/rmagick/issues/834
