### ISSUE TITLE
REST API Interface

### ISSUE THREAD

**Issue by tsjordan-eng** [OpenC3/cosmos#705]
Is there a REST API interface? Many software packages allow you to send a GET or POST to receive date or command package. This is different that the existing TCP interfaces on (at least) two accounts:
* GET/POST not the same as raw TCP
* no streeaming data, requires a GET

This is reminiscent of the Template protocol, but I don't see anything in the docs or codebase that can do this.

**Comment by ryanmelt** [comment]
I think you are referring to #270.
I'm actively working that now.
