### ISSUE TITLE
Interface SECRET ENV doesn't act as documented

### ISSUE THREAD

**Issue by tsjordan-eng** [OpenC3/cosmos#710]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

https://openc3.com/docs/v5/plugins#secret

**Describe the bug**

SECRET ENV vars are not appropriately nameed in thee interface environment, they have the "Secret Name", not the "Enviroment Variable Name".

**To Reproduce**

I have a SECRET declared in my plugin.txt for my interface as such:
```
INTERFACE ...
  SECRET ENV AUTH <%= target_name %>_AUTH
```

But my interface cannot find the `ENV['AUTH']`, but only `ENV['MYTARGET_AUTH']`

**Expected behavior**
The Secret should be set in the GUI with the name `MYTARGET_AUTH`, but should appear to the interface code as `AUTH`

**Environment (please complete the following information):**

- OS: RHEL 7
- OpenC3 COSMOS Version 5.8.1
- Browser
  -- [] Internet Explorer (IE)
  -- [] Google Chrome
  -- [x] Chromium based browsers
  -- [] Mozilla Firefox
  -- [] Safari

**Comment by ryanmelt** [comment]
I think this is just a documentation question.   It appears to be working as expected.  
The name of the secret is AUTH.   You are giving it to the Interface in an environment variable called MYTARGET_AUTH.
You set the name of the secret "AUTH" in the GUI, and the value of the secret.
You can then place the secret into a file, or into an environment variable, for the INTERFACE or MICROSERVICE.
