### ISSUE TITLE
Error developing frontend applications

### ISSUE THREAD

**Issue by mkg880** [OpenC3/cosmos#740]
I am trying to follow the guide to develop openc3 frontend applications as given by https://github.com/OpenC3/cosmos/blob/main/openc3-cosmos-init/plugins/README.md

When I follow these instructions, I get an error in the browser with this single spa minified message:
https://single-spa.js.org/error/?code=37&arg=application&arg=@openc3/tool-tlmgrapher&arg={

**Comment by ryanmelt** [comment]
Try creating your frontend app using our generators.

```
# Make sure openc3.sh is in your path
openc3.sh cli generate plugin testing
cd openc3-cosmos-testing
openc3.sh cli generate tool_vue mytool
yarn
rake build VERSION=1.0.0
```

As of 5.9.0, tool_react, tool_angular, and tool_svelte are also available

**Comment by ryanmelt** [comment]
You can modify/build the main apps individually, just be working on them in their paths under openc3-cosmos-init.
You run yarn from the higher level folder, but then in the individual apps, you can run yarn build or yarn serve.

**Comment by mkg880** [comment]
Yes, that's what I was trying to do initially that gave me the error I linked in my original comment.

**Comment by ryanmelt** [comment]
Going back to supporting 5.4.2 is support contract territory.   Reach out to support@openc3.com if you are interested.

**Comment by mkg880** [comment]
I resolved the issue. An old configuration was being loaded instead of the current one. Running `openc3.sh cleanup` and rebuilding cosmos fixed the issue.
