### ISSUE TITLE
Inject telemetry from protocol

### ISSUE THREAD

**Issue by finchlt** [OpenC3/cosmos#744]
I have a custom protocol that builds and aggregated command buffer made up of many commands. This process is trigger by a command being sent and intercepted in a protocol. When this protocol runs for the given input command target and command, I want to inject a TLM packet back into system with some metadata that can be used for validation of telemetry generated by the aggregated command being executed. 

Is there an easy or best way to inject a TLM packet from a protocol. I tried a bunch of imports but couldn't get the `inject_tlm` function from script api to resolve.

**Comment by ryanmelt** [comment]
inject_tlm can be used by
```
require 'openc3/api/api'
...
class MyProtocol < Protocol
  include Api

  def write_data(...)
    inject_tlm(...)
  end
end
```

You can't ever require 'openc3/script' from interfaces or protocols because those use HTTP to hit the actual API and require credentials.   You can use the API code directly though.

**Comment by finchlt** [comment]
thanks! works perfect!

**Comment by xavier-rangel** [comment]
> inject_tlm can be used by
> 
> ```
> require 'openc3/api/api'
> ...
> class MyProtocol < Protocol
>   include Api
> 
>   def write_data(...)
>     inject_tlm(...)
>   end
> end
> ```
> 
> You can't ever require 'openc3/script' from interfaces or protocols because those use HTTP to hit the actual API and require credentials. You can use the API code directly though.

I have a custom protocol that is using 'openc3/script' for access to inject_tlm(), should I using 'openc3/api/api'?

**Comment by ryanmelt** [comment]
@xavier-rangel Yes, don't use openc3/script (except for scripts).  Internal microservices should use openc3/api/api.
