### ISSUE TITLE
get_target_file in custom protocol

### ISSUE THREAD

**Issue by xavier-rangel** [OpenC3/cosmos#750]
Hello, I was wondering if there is an equivalent for get_target_file() that is usable in a custom protocol, I would like to avoid require 'openc3/script', I might have missed it in the api/api?

Thanks

**Comment by ryanmelt** [comment]
You can use Bucket directly.
https://github.com/OpenC3/cosmos/blob/main/openc3/lib/openc3/utilities/bucket.rb

**Comment by ryanmelt** [comment]
Need to document this somewhere as another user ran into the same thing.
