### ISSUE TITLE
Request to fork "Ball Aerospace Visual Studio Code COSMOS extension"

### ISSUE THREAD

**Issue by jurgensymynck** [OpenC3/cosmos#753]
Hello,

I would like to request that OpenC3 also forks the original Ball Aerospace "COSMOS extension for visual studio code", and make it available on the Visual Studio Markteplace.  
original link: https://marketplace.visualstudio.com/publishers/BallAero

Why? At the moment, I struggle sometimes with telemetry screens, trying to match screen widget keywords with their proper END keyword (http://docs.openc3.com/docs/v5/telemetry-screens#end)
When I know you take up maintenance of this extension, I would like to request a "Cosmos file formatter" or at least a "Parenthesis matching" function.

Thanks for considering this!
gr. Jurgen

**Comment by jmthomas** [comment]
We already have a ticket for this: #415
