### ISSUE TITLE
Support Grafana

### ISSUE THREAD

**Issue by jmthomas** [OpenC3/cosmos#76]
Perhaps push data to InfluxDB with Grafana on top or directly stream data to Grafana

**Comment by tsjordan-eng** [comment]
It looks like it support Prometheus and Grafana: https://openc3.com/docs/v5/monitoring#grafana.
I haven't gotten it working yet, though.

**Comment by jmthomas** [comment]
Can Graphana support plotting states / enumerations. Can it plot equations based on telemetry? Does it support X vs Y plots?Histogram plots? Can it show units? Can it export as image or PDF?

**Comment by tsjordan-eng** [comment]
Is Grafana an enterprise only feature? That link gives a 404

**Comment by ryanmelt** [comment]
At least for now, pushing data out to InfluxDb and subsequent Grafana support is going to be Enterprise only, so that we can properly support it.

We are also looking into doing a direct Grafana plugin for COSMOS.

**Comment by PratikAher20** [comment]
Eagerly waiting for Open source Grafana Support from COSMOS Team!!

**Comment by jmthomas** [comment]
Grafana support is being performed in this repo: https://github.com/OpenC3/grafana-cosmos-datasource. Status will be tracked there. Currently the plugin has been submitted to Grafana for review.
