### ISSUE TITLE
BUTTON for multiple commands and runScript

### ISSUE THREAD

**Issue by jurgensymynck** [OpenC3/cosmos#777]
Hi,

I am creating a button that should run three lines of code: 

1. one to push data to my target, 
2. wait 100 ms
3. retrieve answer from my target

Since JavaScript apparently has no simple wait(0.1) or sleep(0.1) code, I cannot have all the code in one long BUTTON definition line.
I got things working with runScript() using the [BUTTON example code](https://docs.openc3.com/docs/v5/telemetry-screens#button), but only with the more complex 'environment' method.

The documentation hints at passing variables to scripts using 'a hash of environment variables'
```runScript('INST/procedures/script.rb', false, {'VAR': 'VALUE'})```

... but nowhere in the OpenC3 COSMOS demo is this actually demonstrated, it seems.

in  my_screen.txt:
```
BUTTON '0xAA' "runScript('MY_TARGET/procedures/helper/button_01.rb', true, {'BYTE': '0xAA'})"
```
in button_01.rb:
```
cmd("MY_TARGET CMD_PUSH with MY_DATA #{BYTE}")
cmd("MY_TARGET CMD_PUSH with MY_DATA " + BYTE)
wait(0.1)
cmd("MY_TARGET CMD_FETCH")
```
both cmd() lines turn out _NameError : uninitialized constant BYTE_

My questions: can you tell me where my syntax is wrong? or is the ENV method actually the only method to pass variables to scripts via runScript()? 

Thanks! 
Grts. Jurgen

---
For reference, here is the working code with the ENV method:
in  my_screen.txt:
```
BUTTON '0xFF' "var env = {}; env['BYTE'] = '0xFF'; runScript('MY_TARGET/procedures/helper/button_02.rb',true, env)"
```
in button_02.rb:
```
# leave space after MY_DATA!
cmd("MY_TARGET CMD_PUSH with MY_DATA " + ENV['BYTE'])
wait(0.1)
cmd("MY_TARGET CMD_FETCH")
```

**Comment by ryanmelt** [comment]
We will add an example of using ENV to the demo.
