### ISSUE TITLE
'openc3-cosmos-network already exists' error response

### ISSUE THREAD

**Issue by jimhar-mn** [OpenC3/cosmos#783]
Hello,

Looking into Cosmos 5 after using Cosmos 4 in the past.

During installation and plug-in build steps I repeatedly seem to get the following error:

`Error response from daemon: network with name openc3-cosmos-network already exists`

Everything seems to go fine after that message, but I was just wondering what it meant.

Cosmos 5.10.0.  Windows 10.

**Comment by ryanmelt** [comment]
Thanks for checking out COSMOS 5!

That's a Docker error message that happens when you try to create a docker network that already exists.    We try to create that network in several places to make sure it exists.   The error can be safely ignored.

**Comment by ryanmelt** [comment]
On windows it looks like we can pipe the output to NUL

**Comment by ryanmelt** [comment]
We no longer create the network and let docker compose handle it.
