### ISSUE TITLE
Question Regarding the Pulling of openc3 from rubygems

### ISSUE THREAD

**Issue by stephen-ritter** [OpenC3/cosmos#790]
In the `Gemfile`s  for both the [openc3-cosmos-cmd-tlm-api](https://github.com/OpenC3/cosmos/blob/228d2c418fb1ef9b513f711b300ef5791fac7016/openc3-cosmos-cmd-tlm-api/Gemfile#L53) and the [openc3-cosmos-script-runner-api](https://github.com/OpenC3/cosmos/blob/228d2c418fb1ef9b513f711b300ef5791fac7016/openc3-cosmos-script-runner-api/Gemfile#L46) by default they pull the `openc3` gem from https://rubygems.org. When working on this it wasn't clear that the gem that was being used wasn't linked to the code that I had locally, but was instead being downloaded from the web. Would it be better to raise an exception and require that either `OPENC3_DEVEL` or `OPENC3_PATH` is set in the Dockerfiles of `openc3-cosmos-cmd-tlm-api` and `openc3-cosmos-script-runner-api`? I just put `ENV OPENC3_PATH=/openc3/` inside the Dockerfiles and that seemed to work, but I will add that the PR that I have made (https://github.com/OpenC3/cosmos/pull/789) is required to get it to work due to the library files needing to be built. I guess overall it just seems odd that the code I have locally isn't the code that is being used by either of these services.

Possible patch:
```ruby
if ENV['OPENC3_DEVEL']
  gem 'openc3', :path => ENV['OPENC3_DEVEL']
elsif ENV['OPENC3_PATH']
  gem 'openc3', :path => ENV['OPENC3_PATH']
else
  raise "OpenC3 source path not set. Set either OPENC3_DEVEL or OPENC3_PATH to the correct path."
end
```

**Comment by ryanmelt** [comment]
The gem is built and installed in our base image, which is where most things pull the code in the containers.  The /openc3 folder is there to provide a known constant path to some files for other purposes, but is not in the Ruby search path and is not where code is typically used (unless you modify the Dockerfile like you did to add the OPENC3_PATH environment variable).

**Comment by 321github123** [comment]
Just to clarify, are you saying that that "openc3-cmd-tlm-api" does not depend on the web version of the "openc3" gem?   I thought the gemfile defines dependencies and therefore affects the gem lookup path after the gemfile is bundle installed?

https://github.com/OpenC3/cosmos/blob/main/openc3-cosmos-cmd-tlm-api/Dockerfile#L12?

**Comment by ryanmelt** [comment]
The openc3 gem is already locally installed in the container, so the Gemfile just uses the local copy and doesn't have to download it from the web.
