### ISSUE TITLE
Instructions for Plotting Arbitrary 2D Data?

### ISSUE THREAD

**Issue by jliphard** [OpenC3/cosmos#799]
I've started to use OpenC3 but I'm stuck - how do I plot arbitrary real-time 2D data such voltage vs. temperature, or GPS Lat/Lon position packets? This is such a basic capability that it must be possible, but I can't find any instructions for how to do so. This is a yes/no capability that will force change of platform if it's impossible to plot 2D data. Thanks for any pointers or examples...

**Comment by ryanmelt** [comment]
You are referring to X-Y plots, which we have another ticket open for:
https://github.com/OpenC3/cosmos/issues/743

This is currently only available through our Grafana Integration (An Enterprise Edition Feature).
