### ISSUE TITLE
Pass script parameters from telemetry screens

### ISSUE THREAD

**Issue by CharlotteMorrison** [OpenC3/cosmos#84]
Hello,

I would like to be able to pass parameters from a telemetry screen to a script like in Cosmos 4.  I am currently in the process of updating a Cosmos4 project and this functionality is used frequently in the old repo.  Please let me know if this feature is something you are planning to implement, or if you have a suggested method to do this currently.

Thanks again, 
Charlotte

**Comment by ryanmelt** [comment]
Were you passing parameters before using ARGV?   
We support passing parameters in OpenC3 using environment variables, though I need to check and see if that works from telemetry screens.  I'll try it out and add some instructions here in the next few days.

**Comment by CharlotteMorrison** [comment]
We were passing variables through a couple of methods, including ARGV.  I am not picky how they are passed, just need to get a few things from the screens to scripts to 'clone' the previous screen functionality.

**Comment by jwestra-carrastro** [comment]
> Were you passing parameters before using ARGV? We support passing parameters in OpenC3 using environment variables, though I need to check and see if that works from telemetry screens. I'll try it out and add some instructions here in the next few days.

Where was this posted? I would like to know how to pass environmental variables to scripts from a screen.
