### ISSUE TITLE
Append new line to CMD string for Serial Interface

### ISSUE THREAD

**Issue by roobixx** [OpenC3/cosmos#844]
I am using a serial interface to send commands to attached hardware. My commands are simply strings such as SAT_START. 

The cmd sends just fine however on the receiving hardware, ideally it would like to receive a new line (or return) to indicate the end of the command string. 

Is there a simple way of accomplishing this?

I have come up with a janky solution in the receiving side by appending every string with a “@“ sign to indicate the end of the string. 

example: SAT_START@

Would much prefer a simple line ending if possible.

**Comment by roobixx** [comment]
I’m currently using the FIXED protocol it looks like a switch to TERMINATED would accomplish what I’m needing, yes?

**Comment by jmthomas** [comment]
Yes TERMINATED is exactly designed for this type of application

**Comment by roobixx** [comment]
Thanks! It didn’t dawn on me to look at the protocols until after I posted.
