### ISSUE TITLE
Notifications Show Toast doesn't work

### ISSUE THREAD

**Issue by jmthomas** [OpenC3/cosmos#856]
Show Toast was supposed to create popups for notifications as well as pushing them to the bell icon. Now it doesn't display popups or update the bell icon.

**Comment by jmthomas** [comment]
Another user asked if limits notifications could show the limits setting as well as the violation. Currently we have:

`INST HEALTH_STATUS TEMP1 = -82.04769999999999 is RED_LOW (2023/10/03 22:36:29.091)`

So maybe something like:

`INST HEALTH_STATUS TEMP1 = -82.04769999999999 is RED_LOW (-80.0) at 2023/10/03 22:36:29.091`

**Comment by ryanmelt** [comment]
Opened #860 to capture changing the message.  This ticket will just fix the toast bug.
