### ISSUE TITLE
TCP Client connection to external machine on hosts network

### ISSUE THREAD

**Issue by rmslick** [OpenC3/cosmos#867]
I understand how to get data into cosmos by adding the ports the compose.yaml but I do not know how to use the tcp clients from within docker to connect with an external server that is on the hosts network but is not the host itself. Is this possible? Thanks.

**Comment by ryanmelt** [comment]
Docker works like a home network.  You have to open ports to let traffic in, but all external connections are open.
So all you should need is the IP address (or hostname) of the external server and it should be able to connect.
