### ISSUE TITLE
Unix Time Conversion Flexibility

### ISSUE THREAD

**Issue by tsjordan-eng** [OpenC3/cosmos#878]
I have a packet with UNIX_SECONDS and NANO_SECONDS. I was hoping to use the UnixTimeConversion `READ_CONVERSION`, but it expects microseconds, not nanoseconds. It seems I have a couple options:

* Copy this code into my own plugin and change microseconds to nanoseconds
* Create a derived microseconds item and use that
* Submit an MR that changes the `:RAW` packet read to `:CONVERTED` so that I can convert my nanosecond field. (Or give option or specifying other subsecond types)

Did I miss something simpler? What's your recommendation?

**Comment by ryanmelt** [comment]
As you've said, there are lots of options.
Long term I would vote to add more parameters to our conversion class to support different forms of subseconds, and maybe support defining if it reads the values as RAW or CONVERTED.

Short term, I would just copy the file, rename the class, and modify it in your plugin.  Or you could use a GENERIC_READ_CONVERSION.

**Comment by tsjordan-eng** [comment]
I like to enhance the upstream so as I have time I'll try to submit an MR that keeps the current compatibility by default, but allows for a multiplier and the use of :RAW or :CONVERTED.
