### ISSUE TITLE
Adding tool encounters HTTP 500

### ISSUE THREAD

**Issue by timothyscherer** [OpenC3/cosmos#911]
From the admin console, I am trying to add tools (under the tools tab) using the fields at the top of the page.

I first added a tool named "test" with the url "www.google.com", and it worked correctly.

![image](https://github.com/OpenC3/cosmos/assets/68401889/f0e81ecd-1517-499b-b3dc-d9416b149db1)

Then, tried to create a tool named "test2" with the same configuration otherwise, and it fails.

![image](https://github.com/OpenC3/cosmos/assets/68401889/dd55358f-6847-40f6-829a-aa7736de1c1e)

I also tried renaming the "Telemetry Viewer" tool, which also causes issues, but I have no issue changing the link to the tool, or putting it in a category.

![image](https://github.com/OpenC3/cosmos/assets/68401889/0347c3ed-6eec-4fe0-93d6-ce538a3c9829)

I am using this as suggested in #909, as I think this is a wonderful feature!

- OS: Ubuntu 22.04
- OpenC3 COSMOS Version 5.11.3
- Browser
  - [ ] Internet Explorer (IE)
  - [ ] Google Chrome
  - [ ] Chromium based browsers
  - [x] Mozilla Firefox
  - [ ] Safari

**Comment by ryanmelt** [comment]
This is already fixed and will be in our next release:
Fixed as part of https://github.com/OpenC3/cosmos/pull/901

Older versions are effectively limited to one standalone link.

**Comment by ryanmelt** [comment]
closed by #901
