### ISSUE TITLE
File Acces

### ISSUE THREAD

**Issue by mteckes** [OpenC3/cosmos#920]
Hello, 
I am having some issues with having scripts and protocols use the same files. System.targets is not happy in my script with the error: ` RuntimeError : System.instance parameters are required on first call`

My script is able to modify my files in an different plugin's lib folder. 

My protocol is using a System.targets["plugin"].dir with a join to the file path. Looks like the paths are different between to the two. It does the path as `/tmp/d20231109-77-fqyk8p/targets/<MY_TARGET>/lib/my_directory/my_file.csv`.

My question is more what is the best way to have the Protocol and Scripts to have access to the same files. 

Using COSMOS 5.8.1.

**Comment by ryanmelt** [comment]
For scripts you should use the get_target_file method like you were doing originally in the protocol.   Scripts use openc3/script (which is our client api).
