### ISSUE TITLE
Windows 10 IoT and OpenC3

### ISSUE THREAD

**Issue by jimhar-mn** [OpenC3/cosmos#953]
We have a Windows 10 IoT Enterprise LTSC machine with 16GB of RAM.  It has OS build 19044.3693.  I am unclear on how many CPUs it has and can be allocated to Docker.

Do you think this will meet minimum requirements as specified in https://docs.openc3.com/docs/getting-started/installation#prerequisites  

Do you think we could try with less than 8GB allocated to Docker?  We have some other memory intensive processes running concurrently.

Thanks.

**Comment by jmthomas** [comment]
@jimhar-mn let us know if you have success by commenting on the ticket. Thanks!
