### ISSUE TITLE
log_message not located/working on python

### ISSUE THREAD

**Issue by MightyArty** [OpenC3/cosmos#959]
Hey, I saw your API Guide and noticed that on the `cmd` command there is an option for a `log_message` flag to be put on.
But there is no such flag option through the Python API.
The problem is that the logger of the cmd is putting too many arguments to the console, and I want to disable the logger message.

Could you help me with this issue, please?
Thanks a lot.

Best regards, Tom.

**Comment by jmthomas** [comment]
These changes were just performed in #931. They will be in the next release (probably next week).
