### ISSUE TITLE
Getting historical data

### ISSUE THREAD

**Issue by rmslick** [OpenC3/cosmos#977]
I am a little confused on how to programmatically access data stored either in redis or minio buckets from outside of the web interface. Does the JSON RPC API offer any modes of access for querying or loading this data? What is the recommended way to access the data outside of the web interface?

**Comment by jmthomas** [comment]
The [Streaming API](https://docs.openc3.com/docs/development/streaming-api) is how you access data. 

We have a Ruby example here: https://github.com/OpenC3/cosmos/blob/main/openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/procedures/streaming.rb
We have a python example here: https://github.com/OpenC3/cosmos/blob/main/openc3/python/examples/cosmos_web_socket_example.py
