### ISSUE TITLE
Data of type "FLOAT" is auto-converted to "INT" if there are no non-zero decimals

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/cosmos#990]
**Describe the bug**
If a user has a command definition with a parameter of type "FLOAT", and does not include a non-zero decimal in that parameter when sending the command, COSMOS will turn the value into an int. This is problematic for a protocol that utilizes CBOR within it, because the encoded type will be set an "int", rather than the appropriate "float". As of currently, workaround code is required to fix this (See below). Not sure if this is fixed in later COSMOS versions.

**To Reproduce**
with parameter name "timeout", type FLOAT, value -1.01:
cmd("SYSTEM START_TEST with INTERFACE 'my_interface', TIMEOUT -1.01")

with parameter name "timeout", type FLOAT, value -1.0:
cmd("SYSTEM START_TEST with INTERFACE 'my_interface', TIMEOUT -1")

**Screenshots**
![image](https://github.com/OpenC3/cosmos/assets/111302074/ef440831-1312-4c25-88ef-3fcb8459fd61)
![image](https://github.com/OpenC3/cosmos/assets/111302074/c043fa2f-07c7-440e-8f5e-a668d50746ab)
![image](https://github.com/OpenC3/cosmos/assets/111302074/ab8d91e7-e5bc-4042-afc1-018285c07fca)

Edit: Added another screenshot

**Environment (please complete the following information):**
- OS: Linux Ubuntu
- OpenC3 COSMOS Version: 5.8.1
- Browser: N/A

**Comment by jmthomas** [comment]
@GTI-Dakota would you have an opportunity to try this on the current version? If not it seems like you've identified a workaround in your protocol, correct?

**Comment by GTI-Dakota** [comment]
The workaround is good to go for my protocol, but it's a bit of a kludge. In using this method, every packet being sent out must be checked via an API call (get_command) and run a conversion if any data types are specified as "FLOAT".
